// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package monitoringtest

import (
	"github.com/fromforgesoftware/go-kit/monitoring/logger"
	"github.com/fromforgesoftware/go-kit/monitoring/tracer"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMonitor creates a new instance of MockMonitor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMonitor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMonitor {
	mock := &MockMonitor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMonitor is an autogenerated mock type for the Monitor type
type MockMonitor struct {
	mock.Mock
}

type MockMonitor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMonitor) EXPECT() *MockMonitor_Expecter {
	return &MockMonitor_Expecter{mock: &_m.Mock}
}

// Logger provides a mock function for the type MockMonitor
func (_mock *MockMonitor) Logger() logger.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 logger.Logger
	if returnFunc, ok := ret.Get(0).(func() logger.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logger.Logger)
		}
	}
	return r0
}

// MockMonitor_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockMonitor_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockMonitor_Expecter) Logger() *MockMonitor_Logger_Call {
	return &MockMonitor_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockMonitor_Logger_Call) Run(run func()) *MockMonitor_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMonitor_Logger_Call) Return(logger1 logger.Logger) *MockMonitor_Logger_Call {
	_c.Call.Return(logger1)
	return _c
}

func (_c *MockMonitor_Logger_Call) RunAndReturn(run func() logger.Logger) *MockMonitor_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// Tracer provides a mock function for the type MockMonitor
func (_mock *MockMonitor) Tracer() tracer.Tracer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tracer")
	}

	var r0 tracer.Tracer
	if returnFunc, ok := ret.Get(0).(func() tracer.Tracer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tracer.Tracer)
		}
	}
	return r0
}

// MockMonitor_Tracer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tracer'
type MockMonitor_Tracer_Call struct {
	*mock.Call
}

// Tracer is a helper method to define mock.On call
func (_e *MockMonitor_Expecter) Tracer() *MockMonitor_Tracer_Call {
	return &MockMonitor_Tracer_Call{Call: _e.mock.On("Tracer")}
}

func (_c *MockMonitor_Tracer_Call) Run(run func()) *MockMonitor_Tracer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMonitor_Tracer_Call) Return(tracer1 tracer.Tracer) *MockMonitor_Tracer_Call {
	_c.Call.Return(tracer1)
	return _c
}

func (_c *MockMonitor_Tracer_Call) RunAndReturn(run func() tracer.Tracer) *MockMonitor_Tracer_Call {
	_c.Call.Return(run)
	return _c
}
