// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package errorstest

import (
	"github.com/fromforgesoftware/go-kit/errors"
	mock "github.com/stretchr/testify/mock"
)

// NewDetail creates a new instance of Detail. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDetail(t interface {
	mock.TestingT
	Cleanup(func())
}) *Detail {
	mock := &Detail{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Detail is an autogenerated mock type for the Detail type
type Detail struct {
	mock.Mock
}

type Detail_Expecter struct {
	mock *mock.Mock
}

func (_m *Detail) EXPECT() *Detail_Expecter {
	return &Detail_Expecter{mock: &_m.Mock}
}

// Code provides a mock function for the type Detail
func (_mock *Detail) Code() errors.Code {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Code")
	}

	var r0 errors.Code
	if returnFunc, ok := ret.Get(0).(func() errors.Code); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(errors.Code)
	}
	return r0
}

// Detail_Code_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Code'
type Detail_Code_Call struct {
	*mock.Call
}

// Code is a helper method to define mock.On call
func (_e *Detail_Expecter) Code() *Detail_Code_Call {
	return &Detail_Code_Call{Call: _e.mock.On("Code")}
}

func (_c *Detail_Code_Call) Run(run func()) *Detail_Code_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Detail_Code_Call) Return(code errors.Code) *Detail_Code_Call {
	_c.Call.Return(code)
	return _c
}

func (_c *Detail_Code_Call) RunAndReturn(run func() errors.Code) *Detail_Code_Call {
	_c.Call.Return(run)
	return _c
}

// Field provides a mock function for the type Detail
func (_mock *Detail) Field() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Field")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Detail_Field_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Field'
type Detail_Field_Call struct {
	*mock.Call
}

// Field is a helper method to define mock.On call
func (_e *Detail_Expecter) Field() *Detail_Field_Call {
	return &Detail_Field_Call{Call: _e.mock.On("Field")}
}

func (_c *Detail_Field_Call) Run(run func()) *Detail_Field_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Detail_Field_Call) Return(s string) *Detail_Field_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Detail_Field_Call) RunAndReturn(run func() string) *Detail_Field_Call {
	_c.Call.Return(run)
	return _c
}

// Message provides a mock function for the type Detail
func (_mock *Detail) Message() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Message")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Detail_Message_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Message'
type Detail_Message_Call struct {
	*mock.Call
}

// Message is a helper method to define mock.On call
func (_e *Detail_Expecter) Message() *Detail_Message_Call {
	return &Detail_Message_Call{Call: _e.mock.On("Message")}
}

func (_c *Detail_Message_Call) Run(run func()) *Detail_Message_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Detail_Message_Call) Return(s string) *Detail_Message_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Detail_Message_Call) RunAndReturn(run func() string) *Detail_Message_Call {
	_c.Call.Return(run)
	return _c
}

// Value provides a mock function for the type Detail
func (_mock *Detail) Value() interface{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Value")
	}

	var r0 interface{}
	if returnFunc, ok := ret.Get(0).(func() interface{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	return r0
}

// Detail_Value_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Value'
type Detail_Value_Call struct {
	*mock.Call
}

// Value is a helper method to define mock.On call
func (_e *Detail_Expecter) Value() *Detail_Value_Call {
	return &Detail_Value_Call{Call: _e.mock.On("Value")}
}

func (_c *Detail_Value_Call) Run(run func()) *Detail_Value_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Detail_Value_Call) Return(ifaceVal interface{}) *Detail_Value_Call {
	_c.Call.Return(ifaceVal)
	return _c
}

func (_c *Detail_Value_Call) RunAndReturn(run func() interface{}) *Detail_Value_Call {
	_c.Call.Return(run)
	return _c
}
