// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package errorstest

import (
	"time"

	"github.com/fromforgesoftware/go-kit/errors"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc/codes"
)

// NewError creates a new instance of Error. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewError(t interface {
	mock.TestingT
	Cleanup(func())
}) *Error {
	mock := &Error{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Error is an autogenerated mock type for the Error type
type Error struct {
	mock.Mock
}

type Error_Expecter struct {
	mock *mock.Mock
}

func (_m *Error) EXPECT() *Error_Expecter {
	return &Error_Expecter{mock: &_m.Mock}
}

// Cause provides a mock function for the type Error
func (_mock *Error) Cause() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cause")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Error_Cause_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cause'
type Error_Cause_Call struct {
	*mock.Call
}

// Cause is a helper method to define mock.On call
func (_e *Error_Expecter) Cause() *Error_Cause_Call {
	return &Error_Cause_Call{Call: _e.mock.On("Cause")}
}

func (_c *Error_Cause_Call) Run(run func()) *Error_Cause_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Error_Cause_Call) Return(err error) *Error_Cause_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Error_Cause_Call) RunAndReturn(run func() error) *Error_Cause_Call {
	_c.Call.Return(run)
	return _c
}

// Code provides a mock function for the type Error
func (_mock *Error) Code() errors.Code {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Code")
	}

	var r0 errors.Code
	if returnFunc, ok := ret.Get(0).(func() errors.Code); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(errors.Code)
	}
	return r0
}

// Error_Code_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Code'
type Error_Code_Call struct {
	*mock.Call
}

// Code is a helper method to define mock.On call
func (_e *Error_Expecter) Code() *Error_Code_Call {
	return &Error_Code_Call{Call: _e.mock.On("Code")}
}

func (_c *Error_Code_Call) Run(run func()) *Error_Code_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Error_Code_Call) Return(code errors.Code) *Error_Code_Call {
	_c.Call.Return(code)
	return _c
}

func (_c *Error_Code_Call) RunAndReturn(run func() errors.Code) *Error_Code_Call {
	_c.Call.Return(run)
	return _c
}

// Details provides a mock function for the type Error
func (_mock *Error) Details() []errors.Detail {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Details")
	}

	var r0 []errors.Detail
	if returnFunc, ok := ret.Get(0).(func() []errors.Detail); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]errors.Detail)
		}
	}
	return r0
}

// Error_Details_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Details'
type Error_Details_Call struct {
	*mock.Call
}

// Details is a helper method to define mock.On call
func (_e *Error_Expecter) Details() *Error_Details_Call {
	return &Error_Details_Call{Call: _e.mock.On("Details")}
}

func (_c *Error_Details_Call) Run(run func()) *Error_Details_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Error_Details_Call) Return(details []errors.Detail) *Error_Details_Call {
	_c.Call.Return(details)
	return _c
}

func (_c *Error_Details_Call) RunAndReturn(run func() []errors.Detail) *Error_Details_Call {
	_c.Call.Return(run)
	return _c
}

// Error provides a mock function for the type Error
func (_mock *Error) Error() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Error_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type Error_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *Error_Expecter) Error() *Error_Error_Call {
	return &Error_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *Error_Error_Call) Run(run func()) *Error_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Error_Error_Call) Return(s string) *Error_Error_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Error_Error_Call) RunAndReturn(run func() string) *Error_Error_Call {
	_c.Call.Return(run)
	return _c
}

// GRPCCode provides a mock function for the type Error
func (_mock *Error) GRPCCode() codes.Code {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GRPCCode")
	}

	var r0 codes.Code
	if returnFunc, ok := ret.Get(0).(func() codes.Code); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(codes.Code)
	}
	return r0
}

// Error_GRPCCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GRPCCode'
type Error_GRPCCode_Call struct {
	*mock.Call
}

// GRPCCode is a helper method to define mock.On call
func (_e *Error_Expecter) GRPCCode() *Error_GRPCCode_Call {
	return &Error_GRPCCode_Call{Call: _e.mock.On("GRPCCode")}
}

func (_c *Error_GRPCCode_Call) Run(run func()) *Error_GRPCCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Error_GRPCCode_Call) Return(code codes.Code) *Error_GRPCCode_Call {
	_c.Call.Return(code)
	return _c
}

func (_c *Error_GRPCCode_Call) RunAndReturn(run func() codes.Code) *Error_GRPCCode_Call {
	_c.Call.Return(run)
	return _c
}

// HTTPStatus provides a mock function for the type Error
func (_mock *Error) HTTPStatus() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HTTPStatus")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// Error_HTTPStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HTTPStatus'
type Error_HTTPStatus_Call struct {
	*mock.Call
}

// HTTPStatus is a helper method to define mock.On call
func (_e *Error_Expecter) HTTPStatus() *Error_HTTPStatus_Call {
	return &Error_HTTPStatus_Call{Call: _e.mock.On("HTTPStatus")}
}

func (_c *Error_HTTPStatus_Call) Run(run func()) *Error_HTTPStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Error_HTTPStatus_Call) Return(n int) *Error_HTTPStatus_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *Error_HTTPStatus_Call) RunAndReturn(run func() int) *Error_HTTPStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Message provides a mock function for the type Error
func (_mock *Error) Message() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Message")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Error_Message_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Message'
type Error_Message_Call struct {
	*mock.Call
}

// Message is a helper method to define mock.On call
func (_e *Error_Expecter) Message() *Error_Message_Call {
	return &Error_Message_Call{Call: _e.mock.On("Message")}
}

func (_c *Error_Message_Call) Run(run func()) *Error_Message_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Error_Message_Call) Return(s string) *Error_Message_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Error_Message_Call) RunAndReturn(run func() string) *Error_Message_Call {
	_c.Call.Return(run)
	return _c
}

// RequestID provides a mock function for the type Error
func (_mock *Error) RequestID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequestID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Error_RequestID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestID'
type Error_RequestID_Call struct {
	*mock.Call
}

// RequestID is a helper method to define mock.On call
func (_e *Error_Expecter) RequestID() *Error_RequestID_Call {
	return &Error_RequestID_Call{Call: _e.mock.On("RequestID")}
}

func (_c *Error_RequestID_Call) Run(run func()) *Error_RequestID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Error_RequestID_Call) Return(s string) *Error_RequestID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Error_RequestID_Call) RunAndReturn(run func() string) *Error_RequestID_Call {
	_c.Call.Return(run)
	return _c
}

// Service provides a mock function for the type Error
func (_mock *Error) Service() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Service")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Error_Service_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Service'
type Error_Service_Call struct {
	*mock.Call
}

// Service is a helper method to define mock.On call
func (_e *Error_Expecter) Service() *Error_Service_Call {
	return &Error_Service_Call{Call: _e.mock.On("Service")}
}

func (_c *Error_Service_Call) Run(run func()) *Error_Service_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Error_Service_Call) Return(s string) *Error_Service_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Error_Service_Call) RunAndReturn(run func() string) *Error_Service_Call {
	_c.Call.Return(run)
	return _c
}

// Timestamp provides a mock function for the type Error
func (_mock *Error) Timestamp() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Timestamp")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// Error_Timestamp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Timestamp'
type Error_Timestamp_Call struct {
	*mock.Call
}

// Timestamp is a helper method to define mock.On call
func (_e *Error_Expecter) Timestamp() *Error_Timestamp_Call {
	return &Error_Timestamp_Call{Call: _e.mock.On("Timestamp")}
}

func (_c *Error_Timestamp_Call) Run(run func()) *Error_Timestamp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Error_Timestamp_Call) Return(time1 time.Time) *Error_Timestamp_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *Error_Timestamp_Call) RunAndReturn(run func() time.Time) *Error_Timestamp_Call {
	_c.Call.Return(run)
	return _c
}
