// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resourcetest

import (
	mock "github.com/stretchr/testify/mock"
)

// NewListResponse creates a new instance of ListResponse. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListResponse[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *ListResponse[T] {
	mock := &ListResponse[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ListResponse is an autogenerated mock type for the ListResponse type
type ListResponse[T any] struct {
	mock.Mock
}

type ListResponse_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *ListResponse[T]) EXPECT() *ListResponse_Expecter[T] {
	return &ListResponse_Expecter[T]{mock: &_m.Mock}
}

// Results provides a mock function for the type ListResponse
func (_mock *ListResponse[T]) Results() []T {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Results")
	}

	var r0 []T
	if returnFunc, ok := ret.Get(0).(func() []T); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	return r0
}

// ListResponse_Results_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Results'
type ListResponse_Results_Call[T any] struct {
	*mock.Call
}

// Results is a helper method to define mock.On call
func (_e *ListResponse_Expecter[T]) Results() *ListResponse_Results_Call[T] {
	return &ListResponse_Results_Call[T]{Call: _e.mock.On("Results")}
}

func (_c *ListResponse_Results_Call[T]) Run(run func()) *ListResponse_Results_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ListResponse_Results_Call[T]) Return(vs []T) *ListResponse_Results_Call[T] {
	_c.Call.Return(vs)
	return _c
}

func (_c *ListResponse_Results_Call[T]) RunAndReturn(run func() []T) *ListResponse_Results_Call[T] {
	_c.Call.Return(run)
	return _c
}

// TotalCount provides a mock function for the type ListResponse
func (_mock *ListResponse[T]) TotalCount() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TotalCount")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// ListResponse_TotalCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TotalCount'
type ListResponse_TotalCount_Call[T any] struct {
	*mock.Call
}

// TotalCount is a helper method to define mock.On call
func (_e *ListResponse_Expecter[T]) TotalCount() *ListResponse_TotalCount_Call[T] {
	return &ListResponse_TotalCount_Call[T]{Call: _e.mock.On("TotalCount")}
}

func (_c *ListResponse_TotalCount_Call[T]) Run(run func()) *ListResponse_TotalCount_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ListResponse_TotalCount_Call[T]) Return(n int) *ListResponse_TotalCount_Call[T] {
	_c.Call.Return(n)
	return _c
}

func (_c *ListResponse_TotalCount_Call[T]) RunAndReturn(run func() int) *ListResponse_TotalCount_Call[T] {
	_c.Call.Return(run)
	return _c
}
