// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package filtertest

import (
	"github.com/fromforgesoftware/go-kit/filter"
	mock "github.com/stretchr/testify/mock"
)

// NewFieldFilter creates a new instance of FieldFilter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFieldFilter[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *FieldFilter[T] {
	mock := &FieldFilter[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FieldFilter is an autogenerated mock type for the FieldFilter type
type FieldFilter[T any] struct {
	mock.Mock
}

type FieldFilter_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *FieldFilter[T]) EXPECT() *FieldFilter_Expecter[T] {
	return &FieldFilter_Expecter[T]{mock: &_m.Mock}
}

// Name provides a mock function for the type FieldFilter
func (_mock *FieldFilter[T]) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// FieldFilter_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type FieldFilter_Name_Call[T any] struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *FieldFilter_Expecter[T]) Name() *FieldFilter_Name_Call[T] {
	return &FieldFilter_Name_Call[T]{Call: _e.mock.On("Name")}
}

func (_c *FieldFilter_Name_Call[T]) Run(run func()) *FieldFilter_Name_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FieldFilter_Name_Call[T]) Return(s string) *FieldFilter_Name_Call[T] {
	_c.Call.Return(s)
	return _c
}

func (_c *FieldFilter_Name_Call[T]) RunAndReturn(run func() string) *FieldFilter_Name_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Operator provides a mock function for the type FieldFilter
func (_mock *FieldFilter[T]) Operator() filter.Operator {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Operator")
	}

	var r0 filter.Operator
	if returnFunc, ok := ret.Get(0).(func() filter.Operator); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(filter.Operator)
	}
	return r0
}

// FieldFilter_Operator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Operator'
type FieldFilter_Operator_Call[T any] struct {
	*mock.Call
}

// Operator is a helper method to define mock.On call
func (_e *FieldFilter_Expecter[T]) Operator() *FieldFilter_Operator_Call[T] {
	return &FieldFilter_Operator_Call[T]{Call: _e.mock.On("Operator")}
}

func (_c *FieldFilter_Operator_Call[T]) Run(run func()) *FieldFilter_Operator_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FieldFilter_Operator_Call[T]) Return(operator filter.Operator) *FieldFilter_Operator_Call[T] {
	_c.Call.Return(operator)
	return _c
}

func (_c *FieldFilter_Operator_Call[T]) RunAndReturn(run func() filter.Operator) *FieldFilter_Operator_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Value provides a mock function for the type FieldFilter
func (_mock *FieldFilter[T]) Value() T {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Value")
	}

	var r0 T
	if returnFunc, ok := ret.Get(0).(func() T); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	return r0
}

// FieldFilter_Value_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Value'
type FieldFilter_Value_Call[T any] struct {
	*mock.Call
}

// Value is a helper method to define mock.On call
func (_e *FieldFilter_Expecter[T]) Value() *FieldFilter_Value_Call[T] {
	return &FieldFilter_Value_Call[T]{Call: _e.mock.On("Value")}
}

func (_c *FieldFilter_Value_Call[T]) Run(run func()) *FieldFilter_Value_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FieldFilter_Value_Call[T]) Return(v T) *FieldFilter_Value_Call[T] {
	_c.Call.Return(v)
	return _c
}

func (_c *FieldFilter_Value_Call[T]) RunAndReturn(run func() T) *FieldFilter_Value_Call[T] {
	_c.Call.Return(run)
	return _c
}
