// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package querytest

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewCursor creates a new instance of Cursor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCursor(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cursor {
	mock := &Cursor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Cursor is an autogenerated mock type for the Cursor type
type Cursor struct {
	mock.Mock
}

type Cursor_Expecter struct {
	mock *mock.Mock
}

func (_m *Cursor) EXPECT() *Cursor_Expecter {
	return &Cursor_Expecter{mock: &_m.Mock}
}

// CreatedAt provides a mock function for the type Cursor
func (_mock *Cursor) CreatedAt() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreatedAt")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// Cursor_CreatedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatedAt'
type Cursor_CreatedAt_Call struct {
	*mock.Call
}

// CreatedAt is a helper method to define mock.On call
func (_e *Cursor_Expecter) CreatedAt() *Cursor_CreatedAt_Call {
	return &Cursor_CreatedAt_Call{Call: _e.mock.On("CreatedAt")}
}

func (_c *Cursor_CreatedAt_Call) Run(run func()) *Cursor_CreatedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Cursor_CreatedAt_Call) Return(time1 time.Time) *Cursor_CreatedAt_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *Cursor_CreatedAt_Call) RunAndReturn(run func() time.Time) *Cursor_CreatedAt_Call {
	_c.Call.Return(run)
	return _c
}

// Limit provides a mock function for the type Cursor
func (_mock *Cursor) Limit() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Limit")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// Cursor_Limit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Limit'
type Cursor_Limit_Call struct {
	*mock.Call
}

// Limit is a helper method to define mock.On call
func (_e *Cursor_Expecter) Limit() *Cursor_Limit_Call {
	return &Cursor_Limit_Call{Call: _e.mock.On("Limit")}
}

func (_c *Cursor_Limit_Call) Run(run func()) *Cursor_Limit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Cursor_Limit_Call) Return(n int) *Cursor_Limit_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *Cursor_Limit_Call) RunAndReturn(run func() int) *Cursor_Limit_Call {
	_c.Call.Return(run)
	return _c
}

// UUID provides a mock function for the type Cursor
func (_mock *Cursor) UUID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UUID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Cursor_UUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UUID'
type Cursor_UUID_Call struct {
	*mock.Call
}

// UUID is a helper method to define mock.On call
func (_e *Cursor_Expecter) UUID() *Cursor_UUID_Call {
	return &Cursor_UUID_Call{Call: _e.mock.On("UUID")}
}

func (_c *Cursor_UUID_Call) Run(run func()) *Cursor_UUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Cursor_UUID_Call) Return(s string) *Cursor_UUID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Cursor_UUID_Call) RunAndReturn(run func() string) *Cursor_UUID_Call {
	_c.Call.Return(run)
	return _c
}
