// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositorytest

import (
	"context"

	"github.com/fromforgesoftware/go-kit/resource"
	mock "github.com/stretchr/testify/mock"
)

// NewCreatorBatch creates a new instance of CreatorBatch. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreatorBatch[R resource.Resource](t interface {
	mock.TestingT
	Cleanup(func())
}) *CreatorBatch[R] {
	mock := &CreatorBatch[R]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CreatorBatch is an autogenerated mock type for the CreatorBatch type
type CreatorBatch[R resource.Resource] struct {
	mock.Mock
}

type CreatorBatch_Expecter[R resource.Resource] struct {
	mock *mock.Mock
}

func (_m *CreatorBatch[R]) EXPECT() *CreatorBatch_Expecter[R] {
	return &CreatorBatch_Expecter[R]{mock: &_m.Mock}
}

// CreateBatch provides a mock function for the type CreatorBatch
func (_mock *CreatorBatch[R]) CreateBatch(context1 context.Context, vs []R) ([]R, error) {
	ret := _mock.Called(context1, vs)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 []R
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []R) ([]R, error)); ok {
		return returnFunc(context1, vs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []R) []R); ok {
		r0 = returnFunc(context1, vs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]R)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []R) error); ok {
		r1 = returnFunc(context1, vs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CreatorBatch_CreateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatch'
type CreatorBatch_CreateBatch_Call[R resource.Resource] struct {
	*mock.Call
}

// CreateBatch is a helper method to define mock.On call
//   - context1 context.Context
//   - vs []R
func (_e *CreatorBatch_Expecter[R]) CreateBatch(context1 interface{}, vs interface{}) *CreatorBatch_CreateBatch_Call[R] {
	return &CreatorBatch_CreateBatch_Call[R]{Call: _e.mock.On("CreateBatch", context1, vs)}
}

func (_c *CreatorBatch_CreateBatch_Call[R]) Run(run func(context1 context.Context, vs []R)) *CreatorBatch_CreateBatch_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []R
		if args[1] != nil {
			arg1 = args[1].([]R)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CreatorBatch_CreateBatch_Call[R]) Return(vs1 []R, err error) *CreatorBatch_CreateBatch_Call[R] {
	_c.Call.Return(vs1, err)
	return _c
}

func (_c *CreatorBatch_CreateBatch_Call[R]) RunAndReturn(run func(context1 context.Context, vs []R) ([]R, error)) *CreatorBatch_CreateBatch_Call[R] {
	_c.Call.Return(run)
	return _c
}
