// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositorytest

import (
	"context"

	"github.com/fromforgesoftware/go-kit/application/repository"
	"github.com/fromforgesoftware/go-kit/search"
	mock "github.com/stretchr/testify/mock"
)

// NewDeleter creates a new instance of Deleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Deleter {
	mock := &Deleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Deleter is an autogenerated mock type for the Deleter type
type Deleter struct {
	mock.Mock
}

type Deleter_Expecter struct {
	mock *mock.Mock
}

func (_m *Deleter) EXPECT() *Deleter_Expecter {
	return &Deleter_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type Deleter
func (_mock *Deleter) Delete(ctx context.Context, delType repository.DeleteType, opts ...search.Option) error {
	// search.Option
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, delType)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.DeleteType, ...search.Option) error); ok {
		r0 = returnFunc(ctx, delType, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Deleter_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Deleter_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - delType repository.DeleteType
//   - opts ...search.Option
func (_e *Deleter_Expecter) Delete(ctx interface{}, delType interface{}, opts ...interface{}) *Deleter_Delete_Call {
	return &Deleter_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{ctx, delType}, opts...)...)}
}

func (_c *Deleter_Delete_Call) Run(run func(ctx context.Context, delType repository.DeleteType, opts ...search.Option)) *Deleter_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.DeleteType
		if args[1] != nil {
			arg1 = args[1].(repository.DeleteType)
		}
		var arg2 []search.Option
		variadicArgs := make([]search.Option, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Deleter_Delete_Call) Return(err error) *Deleter_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Deleter_Delete_Call) RunAndReturn(run func(ctx context.Context, delType repository.DeleteType, opts ...search.Option) error) *Deleter_Delete_Call {
	_c.Call.Return(run)
	return _c
}
