// Code generated by mockery v2.43.2. DO NOT EDIT.

package repositorytest

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	search "github.com/fromforgesoftware/go-kit/search"
)

// Destroyer is an autogenerated mock type for the Destroyer type
type Destroyer struct {
	mock.Mock
}

type Destroyer_Expecter struct {
	mock *mock.Mock
}

func (_m *Destroyer) EXPECT() *Destroyer_Expecter {
	return &Destroyer_Expecter{mock: &_m.Mock}
}

// Destroy provides a mock function with given fields: _a0, _a1
func (_m *Destroyer) Destroy(_a0 context.Context, _a1 ...search.Option) error {
	_va := make([]interface{}, len(_a1))
	for _i := range _a1 {
		_va[_i] = _a1[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Destroy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...search.Option) error); ok {
		r0 = rf(_a0, _a1...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Destroyer_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type Destroyer_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 ...search.Option
func (_e *Destroyer_Expecter) Destroy(_a0 interface{}, _a1 ...interface{}) *Destroyer_Destroy_Call {
	return &Destroyer_Destroy_Call{Call: _e.mock.On("Destroy",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *Destroyer_Destroy_Call) Run(run func(_a0 context.Context, _a1 ...search.Option)) *Destroyer_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *Destroyer_Destroy_Call) Return(_a0 error) *Destroyer_Destroy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Destroyer_Destroy_Call) RunAndReturn(run func(context.Context, ...search.Option) error) *Destroyer_Destroy_Call {
	_c.Call.Return(run)
	return _c
}

// NewDestroyer creates a new instance of Destroyer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDestroyer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Destroyer {
	mock := &Destroyer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
