// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositorytest

import (
	"github.com/fromforgesoftware/go-kit/application/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewLock creates a new instance of Lock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLock(t interface {
	mock.TestingT
	Cleanup(func())
}) *Lock {
	mock := &Lock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Lock is an autogenerated mock type for the Lock type
type Lock struct {
	mock.Mock
}

type Lock_Expecter struct {
	mock *mock.Mock
}

func (_m *Lock) EXPECT() *Lock_Expecter {
	return &Lock_Expecter{mock: &_m.Mock}
}

// Contains provides a mock function for the type Lock
func (_mock *Lock) Contains(mode repository.LockMode) bool {
	ret := _mock.Called(mode)

	if len(ret) == 0 {
		panic("no return value specified for Contains")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(repository.LockMode) bool); ok {
		r0 = returnFunc(mode)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Lock_Contains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Contains'
type Lock_Contains_Call struct {
	*mock.Call
}

// Contains is a helper method to define mock.On call
//   - mode repository.LockMode
func (_e *Lock_Expecter) Contains(mode interface{}) *Lock_Contains_Call {
	return &Lock_Contains_Call{Call: _e.mock.On("Contains", mode)}
}

func (_c *Lock_Contains_Call) Run(run func(mode repository.LockMode)) *Lock_Contains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 repository.LockMode
		if args[0] != nil {
			arg0 = args[0].(repository.LockMode)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Lock_Contains_Call) Return(b bool) *Lock_Contains_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Lock_Contains_Call) RunAndReturn(run func(mode repository.LockMode) bool) *Lock_Contains_Call {
	_c.Call.Return(run)
	return _c
}

// Level provides a mock function for the type Lock
func (_mock *Lock) Level() repository.LockLevel {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Level")
	}

	var r0 repository.LockLevel
	if returnFunc, ok := ret.Get(0).(func() repository.LockLevel); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(repository.LockLevel)
	}
	return r0
}

// Lock_Level_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Level'
type Lock_Level_Call struct {
	*mock.Call
}

// Level is a helper method to define mock.On call
func (_e *Lock_Expecter) Level() *Lock_Level_Call {
	return &Lock_Level_Call{Call: _e.mock.On("Level")}
}

func (_c *Lock_Level_Call) Run(run func()) *Lock_Level_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Lock_Level_Call) Return(lockLevel repository.LockLevel) *Lock_Level_Call {
	_c.Call.Return(lockLevel)
	return _c
}

func (_c *Lock_Level_Call) RunAndReturn(run func() repository.LockLevel) *Lock_Level_Call {
	_c.Call.Return(run)
	return _c
}

// Modes provides a mock function for the type Lock
func (_mock *Lock) Modes() []repository.LockMode {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Modes")
	}

	var r0 []repository.LockMode
	if returnFunc, ok := ret.Get(0).(func() []repository.LockMode); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.LockMode)
		}
	}
	return r0
}

// Lock_Modes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Modes'
type Lock_Modes_Call struct {
	*mock.Call
}

// Modes is a helper method to define mock.On call
func (_e *Lock_Expecter) Modes() *Lock_Modes_Call {
	return &Lock_Modes_Call{Call: _e.mock.On("Modes")}
}

func (_c *Lock_Modes_Call) Run(run func()) *Lock_Modes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Lock_Modes_Call) Return(lockModes []repository.LockMode) *Lock_Modes_Call {
	_c.Call.Return(lockModes)
	return _c
}

func (_c *Lock_Modes_Call) RunAndReturn(run func() []repository.LockMode) *Lock_Modes_Call {
	_c.Call.Return(run)
	return _c
}
