// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositorytest

import (
	"context"

	"github.com/fromforgesoftware/go-kit/application/repository"
	"github.com/fromforgesoftware/go-kit/resource"
	mock "github.com/stretchr/testify/mock"
)

// NewPatcher creates a new instance of Patcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPatcher[R resource.Resource](t interface {
	mock.TestingT
	Cleanup(func())
}) *Patcher[R] {
	mock := &Patcher[R]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Patcher is an autogenerated mock type for the Patcher type
type Patcher[R resource.Resource] struct {
	mock.Mock
}

type Patcher_Expecter[R resource.Resource] struct {
	mock *mock.Mock
}

func (_m *Patcher[R]) EXPECT() *Patcher_Expecter[R] {
	return &Patcher_Expecter[R]{mock: &_m.Mock}
}

// Patch provides a mock function for the type Patcher
func (_mock *Patcher[R]) Patch(context1 context.Context, patchOptions ...repository.PatchOption) ([]R, error) {
	// repository.PatchOption
	_va := make([]interface{}, len(patchOptions))
	for _i := range patchOptions {
		_va[_i] = patchOptions[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, context1)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 []R
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...repository.PatchOption) ([]R, error)); ok {
		return returnFunc(context1, patchOptions...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...repository.PatchOption) []R); ok {
		r0 = returnFunc(context1, patchOptions...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]R)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...repository.PatchOption) error); ok {
		r1 = returnFunc(context1, patchOptions...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Patcher_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type Patcher_Patch_Call[R resource.Resource] struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - context1 context.Context
//   - patchOptions ...repository.PatchOption
func (_e *Patcher_Expecter[R]) Patch(context1 interface{}, patchOptions ...interface{}) *Patcher_Patch_Call[R] {
	return &Patcher_Patch_Call[R]{Call: _e.mock.On("Patch",
		append([]interface{}{context1}, patchOptions...)...)}
}

func (_c *Patcher_Patch_Call[R]) Run(run func(context1 context.Context, patchOptions ...repository.PatchOption)) *Patcher_Patch_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []repository.PatchOption
		variadicArgs := make([]repository.PatchOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(repository.PatchOption)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Patcher_Patch_Call[R]) Return(vs []R, err error) *Patcher_Patch_Call[R] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *Patcher_Patch_Call[R]) RunAndReturn(run func(context1 context.Context, patchOptions ...repository.PatchOption) ([]R, error)) *Patcher_Patch_Call[R] {
	_c.Call.Return(run)
	return _c
}
