// Code generated by mockery v2.45.1. DO NOT EDIT.

package repositorytest

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	resource "github.com/fromforgesoftware/go-kit/resource"
)

// UpdaterBatch is an autogenerated mock type for the UpdaterBatch type
type UpdaterBatch[R resource.Resource] struct {
	mock.Mock
}

type UpdaterBatch_Expecter[R resource.Resource] struct {
	mock *mock.Mock
}

func (_m *UpdaterBatch[R]) EXPECT() *UpdaterBatch_Expecter[R] {
	return &UpdaterBatch_Expecter[R]{mock: &_m.Mock}
}

// UpdateBatch provides a mock function with given fields: _a0, _a1
func (_m *UpdaterBatch[R]) UpdateBatch(_a0 context.Context, _a1 []R) ([]R, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBatch")
	}

	var r0 []R
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []R) ([]R, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []R) []R); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]R)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []R) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdaterBatch_UpdateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBatch'
type UpdaterBatch_UpdateBatch_Call[R resource.Resource] struct {
	*mock.Call
}

// UpdateBatch is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 []R
func (_e *UpdaterBatch_Expecter[R]) UpdateBatch(_a0 interface{}, _a1 interface{}) *UpdaterBatch_UpdateBatch_Call[R] {
	return &UpdaterBatch_UpdateBatch_Call[R]{Call: _e.mock.On("UpdateBatch", _a0, _a1)}
}

func (_c *UpdaterBatch_UpdateBatch_Call[R]) Run(run func(_a0 context.Context, _a1 []R)) *UpdaterBatch_UpdateBatch_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]R))
	})
	return _c
}

func (_c *UpdaterBatch_UpdateBatch_Call[R]) Return(_a0 []R, _a1 error) *UpdaterBatch_UpdateBatch_Call[R] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UpdaterBatch_UpdateBatch_Call[R]) RunAndReturn(run func(context.Context, []R) ([]R, error)) *UpdaterBatch_UpdateBatch_Call[R] {
	_c.Call.Return(run)
	return _c
}

// NewUpdaterBatch creates a new instance of UpdaterBatch. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdaterBatch[R resource.Resource](t interface {
	mock.TestingT
	Cleanup(func())
}) *UpdaterBatch[R] {
	mock := &UpdaterBatch[R]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
