// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jwttest

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewIssuer creates a new instance of Issuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Issuer {
	mock := &Issuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Issuer is an autogenerated mock type for the Issuer type
type Issuer struct {
	mock.Mock
}

type Issuer_Expecter struct {
	mock *mock.Mock
}

func (_m *Issuer) EXPECT() *Issuer_Expecter {
	return &Issuer_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function for the type Issuer
func (_mock *Issuer) Issue(ctx context.Context, accountID uuid.UUID, username string) (string, error) {
	ret := _mock.Called(ctx, accountID, username)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (string, error)); ok {
		return returnFunc(ctx, accountID, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) string); ok {
		r0 = returnFunc(ctx, accountID, username)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, accountID, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Issuer_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type Issuer_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID uuid.UUID
//   - username string
func (_e *Issuer_Expecter) Issue(ctx interface{}, accountID interface{}, username interface{}) *Issuer_Issue_Call {
	return &Issuer_Issue_Call{Call: _e.mock.On("Issue", ctx, accountID, username)}
}

func (_c *Issuer_Issue_Call) Run(run func(ctx context.Context, accountID uuid.UUID, username string)) *Issuer_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Issuer_Issue_Call) Return(s string, err error) *Issuer_Issue_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Issuer_Issue_Call) RunAndReturn(run func(ctx context.Context, accountID uuid.UUID, username string) (string, error)) *Issuer_Issue_Call {
	_c.Call.Return(run)
	return _c
}
