// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jwttest

import (
	"context"

	"github.com/fromforgesoftware/go-kit/auth/jwt"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewIssuerValidator creates a new instance of IssuerValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIssuerValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *IssuerValidator {
	mock := &IssuerValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IssuerValidator is an autogenerated mock type for the IssuerValidator type
type IssuerValidator struct {
	mock.Mock
}

type IssuerValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *IssuerValidator) EXPECT() *IssuerValidator_Expecter {
	return &IssuerValidator_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function for the type IssuerValidator
func (_mock *IssuerValidator) Issue(ctx context.Context, accountID uuid.UUID, username string) (string, error) {
	ret := _mock.Called(ctx, accountID, username)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (string, error)); ok {
		return returnFunc(ctx, accountID, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) string); ok {
		r0 = returnFunc(ctx, accountID, username)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, accountID, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IssuerValidator_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type IssuerValidator_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID uuid.UUID
//   - username string
func (_e *IssuerValidator_Expecter) Issue(ctx interface{}, accountID interface{}, username interface{}) *IssuerValidator_Issue_Call {
	return &IssuerValidator_Issue_Call{Call: _e.mock.On("Issue", ctx, accountID, username)}
}

func (_c *IssuerValidator_Issue_Call) Run(run func(ctx context.Context, accountID uuid.UUID, username string)) *IssuerValidator_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *IssuerValidator_Issue_Call) Return(s string, err error) *IssuerValidator_Issue_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *IssuerValidator_Issue_Call) RunAndReturn(run func(ctx context.Context, accountID uuid.UUID, username string) (string, error)) *IssuerValidator_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function for the type IssuerValidator
func (_mock *IssuerValidator) Validate(ctx context.Context, token string) (*jwt.Claims, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 *jwt.Claims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*jwt.Claims, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *jwt.Claims); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Claims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// IssuerValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type IssuerValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *IssuerValidator_Expecter) Validate(ctx interface{}, token interface{}) *IssuerValidator_Validate_Call {
	return &IssuerValidator_Validate_Call{Call: _e.mock.On("Validate", ctx, token)}
}

func (_c *IssuerValidator_Validate_Call) Run(run func(ctx context.Context, token string)) *IssuerValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *IssuerValidator_Validate_Call) Return(claims *jwt.Claims, err error) *IssuerValidator_Validate_Call {
	_c.Call.Return(claims, err)
	return _c
}

func (_c *IssuerValidator_Validate_Call) RunAndReturn(run func(ctx context.Context, token string) (*jwt.Claims, error)) *IssuerValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}
