// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jwttest

import (
	"context"

	"github.com/fromforgesoftware/go-kit/auth/jwt"
	mock "github.com/stretchr/testify/mock"
)

// NewValidator creates a new instance of Validator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Validator {
	mock := &Validator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Validator is an autogenerated mock type for the Validator type
type Validator struct {
	mock.Mock
}

type Validator_Expecter struct {
	mock *mock.Mock
}

func (_m *Validator) EXPECT() *Validator_Expecter {
	return &Validator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type Validator
func (_mock *Validator) Validate(ctx context.Context, token string) (*jwt.Claims, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 *jwt.Claims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*jwt.Claims, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *jwt.Claims); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Claims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Validator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type Validator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *Validator_Expecter) Validate(ctx interface{}, token interface{}) *Validator_Validate_Call {
	return &Validator_Validate_Call{Call: _e.mock.On("Validate", ctx, token)}
}

func (_c *Validator_Validate_Call) Run(run func(ctx context.Context, token string)) *Validator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Validator_Validate_Call) Return(claims *jwt.Claims, err error) *Validator_Validate_Call {
	_c.Call.Return(claims, err)
	return _c
}

func (_c *Validator_Validate_Call) RunAndReturn(run func(ctx context.Context, token string) (*jwt.Claims, error)) *Validator_Validate_Call {
	_c.Call.Return(run)
	return _c
}
