// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecasetest

import (
	"context"

	"github.com/fromforgesoftware/go-kit/resource"
	mock "github.com/stretchr/testify/mock"
)

// NewCreator creates a new instance of Creator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreator[R resource.Resource](t interface {
	mock.TestingT
	Cleanup(func())
}) *Creator[R] {
	mock := &Creator[R]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Creator is an autogenerated mock type for the Creator type
type Creator[R resource.Resource] struct {
	mock.Mock
}

type Creator_Expecter[R resource.Resource] struct {
	mock *mock.Mock
}

func (_m *Creator[R]) EXPECT() *Creator_Expecter[R] {
	return &Creator_Expecter[R]{mock: &_m.Mock}
}

// Create provides a mock function for the type Creator
func (_mock *Creator[R]) Create(ctx context.Context, r R) (R, error) {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 R
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, R) (R, error)); ok {
		return returnFunc(ctx, r)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, R) R); ok {
		r0 = returnFunc(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(R)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, R) error); ok {
		r1 = returnFunc(ctx, r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Creator_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Creator_Create_Call[R resource.Resource] struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - r R
func (_e *Creator_Expecter[R]) Create(ctx interface{}, r interface{}) *Creator_Create_Call[R] {
	return &Creator_Create_Call[R]{Call: _e.mock.On("Create", ctx, r)}
}

func (_c *Creator_Create_Call[R]) Run(run func(ctx context.Context, r R)) *Creator_Create_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 R
		if args[1] != nil {
			arg1 = args[1].(R)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Creator_Create_Call[R]) Return(v R, err error) *Creator_Create_Call[R] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Creator_Create_Call[R]) RunAndReturn(run func(ctx context.Context, r R) (R, error)) *Creator_Create_Call[R] {
	_c.Call.Return(run)
	return _c
}
