// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecasetest

import (
	"context"

	"github.com/fromforgesoftware/go-kit/resource"
	"github.com/fromforgesoftware/go-kit/search"
	mock "github.com/stretchr/testify/mock"
)

// NewLister creates a new instance of Lister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLister[R resource.Resource](t interface {
	mock.TestingT
	Cleanup(func())
}) *Lister[R] {
	mock := &Lister[R]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Lister is an autogenerated mock type for the Lister type
type Lister[R resource.Resource] struct {
	mock.Mock
}

type Lister_Expecter[R resource.Resource] struct {
	mock *mock.Mock
}

func (_m *Lister[R]) EXPECT() *Lister_Expecter[R] {
	return &Lister_Expecter[R]{mock: &_m.Mock}
}

// List provides a mock function for the type Lister
func (_mock *Lister[R]) List(ctx context.Context, opts ...search.Option) (resource.ListResponse[R], error) {
	// search.Option
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 resource.ListResponse[R]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...search.Option) (resource.ListResponse[R], error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...search.Option) resource.ListResponse[R]); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resource.ListResponse[R])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...search.Option) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Lister_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Lister_List_Call[R resource.Resource] struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...search.Option
func (_e *Lister_Expecter[R]) List(ctx interface{}, opts ...interface{}) *Lister_List_Call[R] {
	return &Lister_List_Call[R]{Call: _e.mock.On("List",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *Lister_List_Call[R]) Run(run func(ctx context.Context, opts ...search.Option)) *Lister_List_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []search.Option
		variadicArgs := make([]search.Option, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(search.Option)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Lister_List_Call[R]) Return(listResponse resource.ListResponse[R], err error) *Lister_List_Call[R] {
	_c.Call.Return(listResponse, err)
	return _c
}

func (_c *Lister_List_Call[R]) RunAndReturn(run func(ctx context.Context, opts ...search.Option) (resource.ListResponse[R], error)) *Lister_List_Call[R] {
	_c.Call.Return(run)
	return _c
}
