// Code generated by mockery v2.45.1. DO NOT EDIT.

package usecasetest

import (
	context "context"

	resource "github.com/fromforgesoftware/go-kit/resource"
	mock "github.com/stretchr/testify/mock"
)

// PatcherBatch is an autogenerated mock type for the PatcherBatch type
type PatcherBatch[T resource.Resource, R resource.Resource] struct {
	mock.Mock
}

type PatcherBatch_Expecter[T resource.Resource, R resource.Resource] struct {
	mock *mock.Mock
}

func (_m *PatcherBatch[T, R]) EXPECT() *PatcherBatch_Expecter[T, R] {
	return &PatcherBatch_Expecter[T, R]{mock: &_m.Mock}
}

// PatchBatch provides a mock function with given fields: ctx, req
func (_m *PatcherBatch[T, R]) PatchBatch(ctx context.Context, req T) ([]R, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for PatchBatch")
	}

	var r0 []R
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, T) ([]R, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, T) []R); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]R)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, T) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PatcherBatch_PatchBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchBatch'
type PatcherBatch_PatchBatch_Call[T resource.Resource, R resource.Resource] struct {
	*mock.Call
}

// PatchBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - req T
func (_e *PatcherBatch_Expecter[T, R]) PatchBatch(ctx interface{}, req interface{}) *PatcherBatch_PatchBatch_Call[T, R] {
	return &PatcherBatch_PatchBatch_Call[T, R]{Call: _e.mock.On("PatchBatch", ctx, req)}
}

func (_c *PatcherBatch_PatchBatch_Call[T, R]) Run(run func(ctx context.Context, req T)) *PatcherBatch_PatchBatch_Call[T, R] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(T))
	})
	return _c
}

func (_c *PatcherBatch_PatchBatch_Call[T, R]) Return(_a0 []R, _a1 error) *PatcherBatch_PatchBatch_Call[T, R] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PatcherBatch_PatchBatch_Call[T, R]) RunAndReturn(run func(context.Context, T) ([]R, error)) *PatcherBatch_PatchBatch_Call[T, R] {
	_c.Call.Return(run)
	return _c
}

// NewPatcherBatch creates a new instance of PatcherBatch. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPatcherBatch[T resource.Resource, R resource.Resource](t interface {
	mock.TestingT
	Cleanup(func())
}) *PatcherBatch[T, R] {
	mock := &PatcherBatch[T, R]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
