// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecasetest

import (
	"context"

	"github.com/fromforgesoftware/go-kit/resource"
	mock "github.com/stretchr/testify/mock"
)

// NewUpdater creates a new instance of Updater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdater[R resource.Resource](t interface {
	mock.TestingT
	Cleanup(func())
}) *Updater[R] {
	mock := &Updater[R]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Updater is an autogenerated mock type for the Updater type
type Updater[R resource.Resource] struct {
	mock.Mock
}

type Updater_Expecter[R resource.Resource] struct {
	mock *mock.Mock
}

func (_m *Updater[R]) EXPECT() *Updater_Expecter[R] {
	return &Updater_Expecter[R]{mock: &_m.Mock}
}

// Update provides a mock function for the type Updater
func (_mock *Updater[R]) Update(ctx context.Context, req R) (R, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 R
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, R) (R, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, R) R); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(R)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, R) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Updater_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Updater_Update_Call[R resource.Resource] struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - req R
func (_e *Updater_Expecter[R]) Update(ctx interface{}, req interface{}) *Updater_Update_Call[R] {
	return &Updater_Update_Call[R]{Call: _e.mock.On("Update", ctx, req)}
}

func (_c *Updater_Update_Call[R]) Run(run func(ctx context.Context, req R)) *Updater_Update_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 R
		if args[1] != nil {
			arg1 = args[1].(R)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Updater_Update_Call[R]) Return(v R, err error) *Updater_Update_Call[R] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Updater_Update_Call[R]) RunAndReturn(run func(ctx context.Context, req R) (R, error)) *Updater_Update_Call[R] {
	_c.Call.Return(run)
	return _c
}
