// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package audittest

import (
	"context"

	"github.com/fromforgesoftware/go-kit/audit"
	mock "github.com/stretchr/testify/mock"
)

// NewSink creates a new instance of Sink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSink(t interface {
	mock.TestingT
	Cleanup(func())
}) *Sink {
	mock := &Sink{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Sink is an autogenerated mock type for the Sink type
type Sink struct {
	mock.Mock
}

type Sink_Expecter struct {
	mock *mock.Mock
}

func (_m *Sink) EXPECT() *Sink_Expecter {
	return &Sink_Expecter{mock: &_m.Mock}
}

// Emit provides a mock function for the type Sink
func (_mock *Sink) Emit(ctx context.Context, e audit.Event) error {
	ret := _mock.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for Emit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, audit.Event) error); ok {
		r0 = returnFunc(ctx, e)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Sink_Emit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Emit'
type Sink_Emit_Call struct {
	*mock.Call
}

// Emit is a helper method to define mock.On call
//   - ctx context.Context
//   - e audit.Event
func (_e *Sink_Expecter) Emit(ctx interface{}, e interface{}) *Sink_Emit_Call {
	return &Sink_Emit_Call{Call: _e.mock.On("Emit", ctx, e)}
}

func (_c *Sink_Emit_Call) Run(run func(ctx context.Context, e audit.Event)) *Sink_Emit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 audit.Event
		if args[1] != nil {
			arg1 = args[1].(audit.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Sink_Emit_Call) Return(err error) *Sink_Emit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Sink_Emit_Call) RunAndReturn(run func(ctx context.Context, e audit.Event) error) *Sink_Emit_Call {
	_c.Call.Return(run)
	return _c
}
