// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package websockettest

import (
	"context"

	"github.com/fromforgesoftware/go-kit/transport/websocket"
	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// Read provides a mock function for the type Client
func (_mock *Client) Read() <-chan *websocket.Message {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 <-chan *websocket.Message
	if returnFunc, ok := ret.Get(0).(func() <-chan *websocket.Message); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *websocket.Message)
		}
	}
	return r0
}

// Client_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type Client_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
func (_e *Client_Expecter) Read() *Client_Read_Call {
	return &Client_Read_Call{Call: _e.mock.On("Read")}
}

func (_c *Client_Read_Call) Run(run func()) *Client_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_Read_Call) Return(messageCh <-chan *websocket.Message) *Client_Read_Call {
	_c.Call.Return(messageCh)
	return _c
}

func (_c *Client_Read_Call) RunAndReturn(run func() <-chan *websocket.Message) *Client_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Reconnected provides a mock function for the type Client
func (_mock *Client) Reconnected() <-chan struct{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Reconnected")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// Client_Reconnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reconnected'
type Client_Reconnected_Call struct {
	*mock.Call
}

// Reconnected is a helper method to define mock.On call
func (_e *Client_Expecter) Reconnected() *Client_Reconnected_Call {
	return &Client_Reconnected_Call{Call: _e.mock.On("Reconnected")}
}

func (_c *Client_Reconnected_Call) Run(run func()) *Client_Reconnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_Reconnected_Call) Return(valCh <-chan struct{}) *Client_Reconnected_Call {
	_c.Call.Return(valCh)
	return _c
}

func (_c *Client_Reconnected_Call) RunAndReturn(run func() <-chan struct{}) *Client_Reconnected_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type Client
func (_mock *Client) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type Client_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *Client_Expecter) Start() *Client_Start_Call {
	return &Client_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *Client_Start_Call) Run(run func()) *Client_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_Start_Call) Return(err error) *Client_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_Start_Call) RunAndReturn(run func() error) *Client_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type Client
func (_mock *Client) Stop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type Client_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *Client_Expecter) Stop() *Client_Stop_Call {
	return &Client_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *Client_Stop_Call) Run(run func()) *Client_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_Stop_Call) Return(err error) *Client_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_Stop_Call) RunAndReturn(run func() error) *Client_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type Client
func (_mock *Client) Write(context1 context.Context, message *websocket.Message) <-chan error {
	ret := _mock.Called(context1, message)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 <-chan error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *websocket.Message) <-chan error); ok {
		r0 = returnFunc(context1, message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan error)
		}
	}
	return r0
}

// Client_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type Client_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - context1 context.Context
//   - message *websocket.Message
func (_e *Client_Expecter) Write(context1 interface{}, message interface{}) *Client_Write_Call {
	return &Client_Write_Call{Call: _e.mock.On("Write", context1, message)}
}

func (_c *Client_Write_Call) Run(run func(context1 context.Context, message *websocket.Message)) *Client_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *websocket.Message
		if args[1] != nil {
			arg1 = args[1].(*websocket.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Client_Write_Call) Return(errCh <-chan error) *Client_Write_Call {
	_c.Call.Return(errCh)
	return _c
}

func (_c *Client_Write_Call) RunAndReturn(run func(context1 context.Context, message *websocket.Message) <-chan error) *Client_Write_Call {
	_c.Call.Return(run)
	return _c
}
