// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package websockettest

import (
	"github.com/fromforgesoftware/go-kit/transport/websocket"
	mock "github.com/stretchr/testify/mock"
)

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type Service
func (_mock *Service) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type Service_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *Service_Expecter) Start() *Service_Start_Call {
	return &Service_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *Service_Start_Call) Run(run func()) *Service_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Start_Call) Return(err error) *Service_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_Start_Call) RunAndReturn(run func() error) *Service_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type Service
func (_mock *Service) Stop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type Service_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *Service_Expecter) Stop() *Service_Stop_Call {
	return &Service_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *Service_Stop_Call) Run(run func()) *Service_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Stop_Call) Return(err error) *Service_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_Stop_Call) RunAndReturn(run func() error) *Service_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type Service
func (_mock *Service) Subscribe(topic websocket.TopicType, args []string, callback websocket.WebSocketMessageCallback) (string, error) {
	ret := _mock.Called(topic, args, callback)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(websocket.TopicType, []string, websocket.WebSocketMessageCallback) (string, error)); ok {
		return returnFunc(topic, args, callback)
	}
	if returnFunc, ok := ret.Get(0).(func(websocket.TopicType, []string, websocket.WebSocketMessageCallback) string); ok {
		r0 = returnFunc(topic, args, callback)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(websocket.TopicType, []string, websocket.WebSocketMessageCallback) error); ok {
		r1 = returnFunc(topic, args, callback)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type Service_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - topic websocket.TopicType
//   - args []string
//   - callback websocket.WebSocketMessageCallback
func (_e *Service_Expecter) Subscribe(topic interface{}, args interface{}, callback interface{}) *Service_Subscribe_Call {
	return &Service_Subscribe_Call{Call: _e.mock.On("Subscribe", topic, args, callback)}
}

func (_c *Service_Subscribe_Call) Run(run func(topic websocket.TopicType, args []string, callback websocket.WebSocketMessageCallback)) *Service_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 websocket.TopicType
		if args[0] != nil {
			arg0 = args[0].(websocket.TopicType)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 websocket.WebSocketMessageCallback
		if args[2] != nil {
			arg2 = args[2].(websocket.WebSocketMessageCallback)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Service_Subscribe_Call) Return(s string, err error) *Service_Subscribe_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Service_Subscribe_Call) RunAndReturn(run func(topic websocket.TopicType, args []string, callback websocket.WebSocketMessageCallback) (string, error)) *Service_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function for the type Service
func (_mock *Service) Unsubscribe(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type Service_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - id string
func (_e *Service_Expecter) Unsubscribe(id interface{}) *Service_Unsubscribe_Call {
	return &Service_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe", id)}
}

func (_c *Service_Unsubscribe_Call) Run(run func(id string)) *Service_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_Unsubscribe_Call) Return(err error) *Service_Unsubscribe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_Unsubscribe_Call) RunAndReturn(run func(id string) error) *Service_Unsubscribe_Call {
	_c.Call.Return(run)
	return _c
}
