// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package websockettest

import (
	"github.com/fromforgesoftware/go-kit/transport/websocket"
	mock "github.com/stretchr/testify/mock"
)

// NewTokenProvider creates a new instance of TokenProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenProvider {
	mock := &TokenProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenProvider is an autogenerated mock type for the TokenProvider type
type TokenProvider struct {
	mock.Mock
}

type TokenProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenProvider) EXPECT() *TokenProvider_Expecter {
	return &TokenProvider_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type TokenProvider
func (_mock *TokenProvider) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TokenProvider_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type TokenProvider_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *TokenProvider_Expecter) Close() *TokenProvider_Close_Call {
	return &TokenProvider_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *TokenProvider_Close_Call) Run(run func()) *TokenProvider_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TokenProvider_Close_Call) Return(err error) *TokenProvider_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TokenProvider_Close_Call) RunAndReturn(run func() error) *TokenProvider_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetToken provides a mock function for the type TokenProvider
func (_mock *TokenProvider) GetToken() ([]*websocket.Token, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetToken")
	}

	var r0 []*websocket.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*websocket.Token, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*websocket.Token); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*websocket.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenProvider_GetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToken'
type TokenProvider_GetToken_Call struct {
	*mock.Call
}

// GetToken is a helper method to define mock.On call
func (_e *TokenProvider_Expecter) GetToken() *TokenProvider_GetToken_Call {
	return &TokenProvider_GetToken_Call{Call: _e.mock.On("GetToken")}
}

func (_c *TokenProvider_GetToken_Call) Run(run func()) *TokenProvider_GetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TokenProvider_GetToken_Call) Return(tokens []*websocket.Token, err error) *TokenProvider_GetToken_Call {
	_c.Call.Return(tokens, err)
	return _c
}

func (_c *TokenProvider_GetToken_Call) RunAndReturn(run func() ([]*websocket.Token, error)) *TokenProvider_GetToken_Call {
	_c.Call.Return(run)
	return _c
}
