// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tb/search/v1/query.proto

package searchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operator int32

const (
	Operator_OPERATOR_UNSPECIFIED   Operator = 0
	Operator_OPERATOR_EQ            Operator = 1
	Operator_OPERATOR_NEQ           Operator = 2
	Operator_OPERATOR_GT            Operator = 3
	Operator_OPERATOR_GTEQ          Operator = 4
	Operator_OPERATOR_LT            Operator = 5
	Operator_OPERATOR_LTEQ          Operator = 6
	Operator_OPERATOR_IN            Operator = 7
	Operator_OPERATOR_NOT_IN        Operator = 8
	Operator_OPERATOR_LIKE          Operator = 9
	Operator_OPERATOR_BETWEEN       Operator = 10
	Operator_OPERATOR_CONTAINS      Operator = 11
	Operator_OPERATOR_CONTAINS_LIKE Operator = 12
	Operator_OPERATOR_IS_NULL       Operator = 13
	Operator_OPERATOR_NOT_NULL      Operator = 14
	Operator_OPERATOR_NOT_LIKE      Operator = 15
)

// Enum value maps for Operator.
var (
	Operator_name = map[int32]string{
		0:  "OPERATOR_UNSPECIFIED",
		1:  "OPERATOR_EQ",
		2:  "OPERATOR_NEQ",
		3:  "OPERATOR_GT",
		4:  "OPERATOR_GTEQ",
		5:  "OPERATOR_LT",
		6:  "OPERATOR_LTEQ",
		7:  "OPERATOR_IN",
		8:  "OPERATOR_NOT_IN",
		9:  "OPERATOR_LIKE",
		10: "OPERATOR_BETWEEN",
		11: "OPERATOR_CONTAINS",
		12: "OPERATOR_CONTAINS_LIKE",
		13: "OPERATOR_IS_NULL",
		14: "OPERATOR_NOT_NULL",
		15: "OPERATOR_NOT_LIKE",
	}
	Operator_value = map[string]int32{
		"OPERATOR_UNSPECIFIED":   0,
		"OPERATOR_EQ":            1,
		"OPERATOR_NEQ":           2,
		"OPERATOR_GT":            3,
		"OPERATOR_GTEQ":          4,
		"OPERATOR_LT":            5,
		"OPERATOR_LTEQ":          6,
		"OPERATOR_IN":            7,
		"OPERATOR_NOT_IN":        8,
		"OPERATOR_LIKE":          9,
		"OPERATOR_BETWEEN":       10,
		"OPERATOR_CONTAINS":      11,
		"OPERATOR_CONTAINS_LIKE": 12,
		"OPERATOR_IS_NULL":       13,
		"OPERATOR_NOT_NULL":      14,
		"OPERATOR_NOT_LIKE":      15,
	}
)

func (x Operator) Enum() *Operator {
	p := new(Operator)
	*p = x
	return p
}

func (x Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_tb_search_v1_query_proto_enumTypes[0].Descriptor()
}

func (Operator) Type() protoreflect.EnumType {
	return &file_tb_search_v1_query_proto_enumTypes[0]
}

func (x Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operator.Descriptor instead.
func (Operator) EnumDescriptor() ([]byte, []int) {
	return file_tb_search_v1_query_proto_rawDescGZIP(), []int{0}
}

type QueryOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*Filter              `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Sort          []*Sort                `protobuf:"bytes,3,rep,name=sort,proto3" json:"sort,omitempty"`
	Include       []string               `protobuf:"bytes,4,rep,name=include,proto3" json:"include,omitempty"`
	Fields        []*FieldSet            `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryOptions) Reset() {
	*x = QueryOptions{}
	mi := &file_tb_search_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOptions) ProtoMessage() {}

func (x *QueryOptions) ProtoReflect() protoreflect.Message {
	mi := &file_tb_search_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOptions.ProtoReflect.Descriptor instead.
func (*QueryOptions) Descriptor() ([]byte, []int) {
	return file_tb_search_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryOptions) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *QueryOptions) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *QueryOptions) GetSort() []*Sort {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *QueryOptions) GetInclude() []string {
	if x != nil {
		return x.Include
	}
	return nil
}

func (x *QueryOptions) GetFields() []*FieldSet {
	if x != nil {
		return x.Fields
	}
	return nil
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Operator      Operator               `protobuf:"varint,2,opt,name=operator,proto3,enum=tb.search.v1.Operator" json:"operator,omitempty"`
	Values        []string               `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_tb_search_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_tb_search_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_tb_search_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *Filter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Filter) GetOperator() Operator {
	if x != nil {
		return x.Operator
	}
	return Operator_OPERATOR_UNSPECIFIED
}

func (x *Filter) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Before        string                 `protobuf:"bytes,4,opt,name=before,proto3" json:"before,omitempty"`
	After         string                 `protobuf:"bytes,5,opt,name=after,proto3" json:"after,omitempty"`
	Size          int32                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_tb_search_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_tb_search_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_tb_search_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *Pagination) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Pagination) GetBefore() string {
	if x != nil {
		return x.Before
	}
	return ""
}

func (x *Pagination) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *Pagination) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Sort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Descending    bool                   `protobuf:"varint,2,opt,name=descending,proto3" json:"descending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sort) Reset() {
	*x = Sort{}
	mi := &file_tb_search_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sort) ProtoMessage() {}

func (x *Sort) ProtoReflect() protoreflect.Message {
	mi := &file_tb_search_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sort.ProtoReflect.Descriptor instead.
func (*Sort) Descriptor() ([]byte, []int) {
	return file_tb_search_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *Sort) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Sort) GetDescending() bool {
	if x != nil {
		return x.Descending
	}
	return false
}

type FieldSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Names         []string               `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldSet) Reset() {
	*x = FieldSet{}
	mi := &file_tb_search_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldSet) ProtoMessage() {}

func (x *FieldSet) ProtoReflect() protoreflect.Message {
	mi := &file_tb_search_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldSet.ProtoReflect.Descriptor instead.
func (*FieldSet) Descriptor() ([]byte, []int) {
	return file_tb_search_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *FieldSet) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *FieldSet) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

var File_tb_search_v1_query_proto protoreflect.FileDescriptor

const file_tb_search_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x18tb/search/v1/query.proto\x12\ftb.search.v1\"\xea\x01\n" +
	"\fQueryOptions\x12.\n" +
	"\afilters\x18\x01 \x03(\v2\x14.tb.search.v1.FilterR\afilters\x128\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x18.tb.search.v1.PaginationR\n" +
	"pagination\x12&\n" +
	"\x04sort\x18\x03 \x03(\v2\x12.tb.search.v1.SortR\x04sort\x12\x18\n" +
	"\ainclude\x18\x04 \x03(\tR\ainclude\x12.\n" +
	"\x06fields\x18\x05 \x03(\v2\x16.tb.search.v1.FieldSetR\x06fields\"j\n" +
	"\x06Filter\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x122\n" +
	"\boperator\x18\x02 \x01(\x0e2\x16.tb.search.v1.OperatorR\boperator\x12\x16\n" +
	"\x06values\x18\x03 \x03(\tR\x06values\"\x8a\x01\n" +
	"\n" +
	"Pagination\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06before\x18\x04 \x01(\tR\x06before\x12\x14\n" +
	"\x05after\x18\x05 \x01(\tR\x05after\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x05R\x04sizeJ\x04\b\x03\x10\x04R\x06cursor\"<\n" +
	"\x04Sort\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1e\n" +
	"\n" +
	"descending\x18\x02 \x01(\bR\n" +
	"descending\"E\n" +
	"\bFieldSet\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names*\xd5\x02\n" +
	"\bOperator\x12\x18\n" +
	"\x14OPERATOR_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vOPERATOR_EQ\x10\x01\x12\x10\n" +
	"\fOPERATOR_NEQ\x10\x02\x12\x0f\n" +
	"\vOPERATOR_GT\x10\x03\x12\x11\n" +
	"\rOPERATOR_GTEQ\x10\x04\x12\x0f\n" +
	"\vOPERATOR_LT\x10\x05\x12\x11\n" +
	"\rOPERATOR_LTEQ\x10\x06\x12\x0f\n" +
	"\vOPERATOR_IN\x10\a\x12\x13\n" +
	"\x0fOPERATOR_NOT_IN\x10\b\x12\x11\n" +
	"\rOPERATOR_LIKE\x10\t\x12\x14\n" +
	"\x10OPERATOR_BETWEEN\x10\n" +
	"\x12\x15\n" +
	"\x11OPERATOR_CONTAINS\x10\v\x12\x1a\n" +
	"\x16OPERATOR_CONTAINS_LIKE\x10\f\x12\x14\n" +
	"\x10OPERATOR_IS_NULL\x10\r\x12\x15\n" +
	"\x11OPERATOR_NOT_NULL\x10\x0e\x12\x15\n" +
	"\x11OPERATOR_NOT_LIKE\x10\x0fB\xb1\x01\n" +
	"\x10com.tb.search.v1B\n" +
	"QueryProtoP\x01Z?github.com/fromforgesoftware/go-kit/proto/tb/search/v1;searchv1\xa2\x02\x03TSX\xaa\x02\fTb.Search.V1\xca\x02\fTb\\Search\\V1\xe2\x02\x18Tb\\Search\\V1\\GPBMetadata\xea\x02\x0eTb::Search::V1b\x06proto3"

var (
	file_tb_search_v1_query_proto_rawDescOnce sync.Once
	file_tb_search_v1_query_proto_rawDescData []byte
)

func file_tb_search_v1_query_proto_rawDescGZIP() []byte {
	file_tb_search_v1_query_proto_rawDescOnce.Do(func() {
		file_tb_search_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tb_search_v1_query_proto_rawDesc), len(file_tb_search_v1_query_proto_rawDesc)))
	})
	return file_tb_search_v1_query_proto_rawDescData
}

var file_tb_search_v1_query_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tb_search_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_tb_search_v1_query_proto_goTypes = []any{
	(Operator)(0),        // 0: tb.search.v1.Operator
	(*QueryOptions)(nil), // 1: tb.search.v1.QueryOptions
	(*Filter)(nil),       // 2: tb.search.v1.Filter
	(*Pagination)(nil),   // 3: tb.search.v1.Pagination
	(*Sort)(nil),         // 4: tb.search.v1.Sort
	(*FieldSet)(nil),     // 5: tb.search.v1.FieldSet
}
var file_tb_search_v1_query_proto_depIdxs = []int32{
	2, // 0: tb.search.v1.QueryOptions.filters:type_name -> tb.search.v1.Filter
	3, // 1: tb.search.v1.QueryOptions.pagination:type_name -> tb.search.v1.Pagination
	4, // 2: tb.search.v1.QueryOptions.sort:type_name -> tb.search.v1.Sort
	5, // 3: tb.search.v1.QueryOptions.fields:type_name -> tb.search.v1.FieldSet
	0, // 4: tb.search.v1.Filter.operator:type_name -> tb.search.v1.Operator
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_tb_search_v1_query_proto_init() }
func file_tb_search_v1_query_proto_init() {
	if File_tb_search_v1_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tb_search_v1_query_proto_rawDesc), len(file_tb_search_v1_query_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tb_search_v1_query_proto_goTypes,
		DependencyIndexes: file_tb_search_v1_query_proto_depIdxs,
		EnumInfos:         file_tb_search_v1_query_proto_enumTypes,
		MessageInfos:      file_tb_search_v1_query_proto_msgTypes,
	}.Build()
	File_tb_search_v1_query_proto = out.File
	file_tb_search_v1_query_proto_goTypes = nil
	file_tb_search_v1_query_proto_depIdxs = nil
}
