// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resttest

import (
	"github.com/fromforgesoftware/go-kit/transport/rest"
	mock "github.com/stretchr/testify/mock"
)

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

type Controller_Expecter struct {
	mock *mock.Mock
}

func (_m *Controller) EXPECT() *Controller_Expecter {
	return &Controller_Expecter{mock: &_m.Mock}
}

// Routes provides a mock function for the type Controller
func (_mock *Controller) Routes(r rest.Router) {
	_mock.Called(r)
	return
}

// Controller_Routes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Routes'
type Controller_Routes_Call struct {
	*mock.Call
}

// Routes is a helper method to define mock.On call
//   - r rest.Router
func (_e *Controller_Expecter) Routes(r interface{}) *Controller_Routes_Call {
	return &Controller_Routes_Call{Call: _e.mock.On("Routes", r)}
}

func (_c *Controller_Routes_Call) Run(run func(r rest.Router)) *Controller_Routes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 rest.Router
		if args[0] != nil {
			arg0 = args[0].(rest.Router)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Controller_Routes_Call) Return() *Controller_Routes_Call {
	_c.Call.Return()
	return _c
}

func (_c *Controller_Routes_Call) RunAndReturn(run func(r rest.Router)) *Controller_Routes_Call {
	_c.Run(run)
	return _c
}
