// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resttest

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewEndpoint creates a new instance of Endpoint. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEndpoint(t interface {
	mock.TestingT
	Cleanup(func())
}) *Endpoint {
	mock := &Endpoint{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Endpoint is an autogenerated mock type for the Endpoint type
type Endpoint struct {
	mock.Mock
}

type Endpoint_Expecter struct {
	mock *mock.Mock
}

func (_m *Endpoint) EXPECT() *Endpoint_Expecter {
	return &Endpoint_Expecter{mock: &_m.Mock}
}

// Method provides a mock function for the type Endpoint
func (_mock *Endpoint) Method() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Method")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Endpoint_Method_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Method'
type Endpoint_Method_Call struct {
	*mock.Call
}

// Method is a helper method to define mock.On call
func (_e *Endpoint_Expecter) Method() *Endpoint_Method_Call {
	return &Endpoint_Method_Call{Call: _e.mock.On("Method")}
}

func (_c *Endpoint_Method_Call) Run(run func()) *Endpoint_Method_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Endpoint_Method_Call) Return(s string) *Endpoint_Method_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Endpoint_Method_Call) RunAndReturn(run func() string) *Endpoint_Method_Call {
	_c.Call.Return(run)
	return _c
}

// Path provides a mock function for the type Endpoint
func (_mock *Endpoint) Path() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Path")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Endpoint_Path_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Path'
type Endpoint_Path_Call struct {
	*mock.Call
}

// Path is a helper method to define mock.On call
func (_e *Endpoint_Expecter) Path() *Endpoint_Path_Call {
	return &Endpoint_Path_Call{Call: _e.mock.On("Path")}
}

func (_c *Endpoint_Path_Call) Run(run func()) *Endpoint_Path_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Endpoint_Path_Call) Return(s string) *Endpoint_Path_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Endpoint_Path_Call) RunAndReturn(run func() string) *Endpoint_Path_Call {
	_c.Call.Return(run)
	return _c
}

// ServeHTTP provides a mock function for the type Endpoint
func (_mock *Endpoint) ServeHTTP(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// Endpoint_ServeHTTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServeHTTP'
type Endpoint_ServeHTTP_Call struct {
	*mock.Call
}

// ServeHTTP is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *Endpoint_Expecter) ServeHTTP(responseWriter interface{}, request interface{}) *Endpoint_ServeHTTP_Call {
	return &Endpoint_ServeHTTP_Call{Call: _e.mock.On("ServeHTTP", responseWriter, request)}
}

func (_c *Endpoint_ServeHTTP_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *Endpoint_ServeHTTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Endpoint_ServeHTTP_Call) Return() *Endpoint_ServeHTTP_Call {
	_c.Call.Return()
	return _c
}

func (_c *Endpoint_ServeHTTP_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *Endpoint_ServeHTTP_Call {
	_c.Run(run)
	return _c
}
