// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resttest

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewHeaderer creates a new instance of Headerer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHeaderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Headerer {
	mock := &Headerer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Headerer is an autogenerated mock type for the Headerer type
type Headerer struct {
	mock.Mock
}

type Headerer_Expecter struct {
	mock *mock.Mock
}

func (_m *Headerer) EXPECT() *Headerer_Expecter {
	return &Headerer_Expecter{mock: &_m.Mock}
}

// Headers provides a mock function for the type Headerer
func (_mock *Headerer) Headers() http.Header {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Headers")
	}

	var r0 http.Header
	if returnFunc, ok := ret.Get(0).(func() http.Header); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Header)
		}
	}
	return r0
}

// Headerer_Headers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Headers'
type Headerer_Headers_Call struct {
	*mock.Call
}

// Headers is a helper method to define mock.On call
func (_e *Headerer_Expecter) Headers() *Headerer_Headers_Call {
	return &Headerer_Headers_Call{Call: _e.mock.On("Headers")}
}

func (_c *Headerer_Headers_Call) Run(run func()) *Headerer_Headers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Headerer_Headers_Call) Return(header http.Header) *Headerer_Headers_Call {
	_c.Call.Return(header)
	return _c
}

func (_c *Headerer_Headers_Call) RunAndReturn(run func() http.Header) *Headerer_Headers_Call {
	_c.Call.Return(run)
	return _c
}
