// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resttest

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewHTTPAuthenticator creates a new instance of HTTPAuthenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHTTPAuthenticator(t interface {
	mock.TestingT
	Cleanup(func())
}) *HTTPAuthenticator {
	mock := &HTTPAuthenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HTTPAuthenticator is an autogenerated mock type for the HTTPAuthenticator type
type HTTPAuthenticator struct {
	mock.Mock
}

type HTTPAuthenticator_Expecter struct {
	mock *mock.Mock
}

func (_m *HTTPAuthenticator) EXPECT() *HTTPAuthenticator_Expecter {
	return &HTTPAuthenticator_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type HTTPAuthenticator
func (_mock *HTTPAuthenticator) Authenticate(req *http.Request) error {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request) error); ok {
		r0 = returnFunc(req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// HTTPAuthenticator_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type HTTPAuthenticator_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - req *http.Request
func (_e *HTTPAuthenticator_Expecter) Authenticate(req interface{}) *HTTPAuthenticator_Authenticate_Call {
	return &HTTPAuthenticator_Authenticate_Call{Call: _e.mock.On("Authenticate", req)}
}

func (_c *HTTPAuthenticator_Authenticate_Call) Run(run func(req *http.Request)) *HTTPAuthenticator_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HTTPAuthenticator_Authenticate_Call) Return(err error) *HTTPAuthenticator_Authenticate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *HTTPAuthenticator_Authenticate_Call) RunAndReturn(run func(req *http.Request) error) *HTTPAuthenticator_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}
