// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resttest

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMiddleware creates a new instance of Middleware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMiddleware(t interface {
	mock.TestingT
	Cleanup(func())
}) *Middleware {
	mock := &Middleware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Middleware is an autogenerated mock type for the Middleware type
type Middleware struct {
	mock.Mock
}

type Middleware_Expecter struct {
	mock *mock.Mock
}

func (_m *Middleware) EXPECT() *Middleware_Expecter {
	return &Middleware_Expecter{mock: &_m.Mock}
}

// Intercept provides a mock function for the type Middleware
func (_mock *Middleware) Intercept(handler http.Handler) http.Handler {
	ret := _mock.Called(handler)

	if len(ret) == 0 {
		panic("no return value specified for Intercept")
	}

	var r0 http.Handler
	if returnFunc, ok := ret.Get(0).(func(http.Handler) http.Handler); ok {
		r0 = returnFunc(handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}
	return r0
}

// Middleware_Intercept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Intercept'
type Middleware_Intercept_Call struct {
	*mock.Call
}

// Intercept is a helper method to define mock.On call
//   - handler http.Handler
func (_e *Middleware_Expecter) Intercept(handler interface{}) *Middleware_Intercept_Call {
	return &Middleware_Intercept_Call{Call: _e.mock.On("Intercept", handler)}
}

func (_c *Middleware_Intercept_Call) Run(run func(handler http.Handler)) *Middleware_Intercept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.Handler
		if args[0] != nil {
			arg0 = args[0].(http.Handler)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Middleware_Intercept_Call) Return(handler1 http.Handler) *Middleware_Intercept_Call {
	_c.Call.Return(handler1)
	return _c
}

func (_c *Middleware_Intercept_Call) RunAndReturn(run func(handler http.Handler) http.Handler) *Middleware_Intercept_Call {
	_c.Call.Return(run)
	return _c
}
