// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resttest

import (
	mock "github.com/stretchr/testify/mock"
)

// NewStatusCoder creates a new instance of StatusCoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatusCoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatusCoder {
	mock := &StatusCoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StatusCoder is an autogenerated mock type for the StatusCoder type
type StatusCoder struct {
	mock.Mock
}

type StatusCoder_Expecter struct {
	mock *mock.Mock
}

func (_m *StatusCoder) EXPECT() *StatusCoder_Expecter {
	return &StatusCoder_Expecter{mock: &_m.Mock}
}

// StatusCode provides a mock function for the type StatusCoder
func (_mock *StatusCoder) StatusCode() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StatusCode")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// StatusCoder_StatusCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatusCode'
type StatusCoder_StatusCode_Call struct {
	*mock.Call
}

// StatusCode is a helper method to define mock.On call
func (_e *StatusCoder_Expecter) StatusCode() *StatusCoder_StatusCode_Call {
	return &StatusCoder_StatusCode_Call{Call: _e.mock.On("StatusCode")}
}

func (_c *StatusCoder_StatusCode_Call) Run(run func()) *StatusCoder_StatusCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StatusCoder_StatusCode_Call) Return(n int) *StatusCoder_StatusCode_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *StatusCoder_StatusCode_Call) RunAndReturn(run func() int) *StatusCoder_StatusCode_Call {
	_c.Call.Return(run)
	return _c
}
