// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tracertest

import (
	"github.com/fromforgesoftware/go-kit/monitoring/tracer"
	mock "github.com/stretchr/testify/mock"
)

// NewSpan creates a new instance of Span. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSpan(t interface {
	mock.TestingT
	Cleanup(func())
}) *Span {
	mock := &Span{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Span is an autogenerated mock type for the Span type
type Span struct {
	mock.Mock
}

type Span_Expecter struct {
	mock *mock.Mock
}

func (_m *Span) EXPECT() *Span_Expecter {
	return &Span_Expecter{mock: &_m.Mock}
}

// AddEvent provides a mock function for the type Span
func (_mock *Span) AddEvent(name string, attrs ...tracer.Attribute) {
	// tracer.Attribute
	_va := make([]interface{}, len(attrs))
	for _i := range attrs {
		_va[_i] = attrs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, name)
	_ca = append(_ca, _va...)
	_mock.Called(_ca...)
	return
}

// Span_AddEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddEvent'
type Span_AddEvent_Call struct {
	*mock.Call
}

// AddEvent is a helper method to define mock.On call
//   - name string
//   - attrs ...tracer.Attribute
func (_e *Span_Expecter) AddEvent(name interface{}, attrs ...interface{}) *Span_AddEvent_Call {
	return &Span_AddEvent_Call{Call: _e.mock.On("AddEvent",
		append([]interface{}{name}, attrs...)...)}
}

func (_c *Span_AddEvent_Call) Run(run func(name string, attrs ...tracer.Attribute)) *Span_AddEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []tracer.Attribute
		variadicArgs := make([]tracer.Attribute, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(tracer.Attribute)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Span_AddEvent_Call) Return() *Span_AddEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *Span_AddEvent_Call) RunAndReturn(run func(name string, attrs ...tracer.Attribute)) *Span_AddEvent_Call {
	_c.Run(run)
	return _c
}

// End provides a mock function for the type Span
func (_mock *Span) End() {
	_mock.Called()
	return
}

// Span_End_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'End'
type Span_End_Call struct {
	*mock.Call
}

// End is a helper method to define mock.On call
func (_e *Span_Expecter) End() *Span_End_Call {
	return &Span_End_Call{Call: _e.mock.On("End")}
}

func (_c *Span_End_Call) Run(run func()) *Span_End_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Span_End_Call) Return() *Span_End_Call {
	_c.Call.Return()
	return _c
}

func (_c *Span_End_Call) RunAndReturn(run func()) *Span_End_Call {
	_c.Run(run)
	return _c
}

// IsRecording provides a mock function for the type Span
func (_mock *Span) IsRecording() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsRecording")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Span_IsRecording_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRecording'
type Span_IsRecording_Call struct {
	*mock.Call
}

// IsRecording is a helper method to define mock.On call
func (_e *Span_Expecter) IsRecording() *Span_IsRecording_Call {
	return &Span_IsRecording_Call{Call: _e.mock.On("IsRecording")}
}

func (_c *Span_IsRecording_Call) Run(run func()) *Span_IsRecording_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Span_IsRecording_Call) Return(b bool) *Span_IsRecording_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Span_IsRecording_Call) RunAndReturn(run func() bool) *Span_IsRecording_Call {
	_c.Call.Return(run)
	return _c
}

// RecordError provides a mock function for the type Span
func (_mock *Span) RecordError(err error, attrs ...tracer.Attribute) {
	// tracer.Attribute
	_va := make([]interface{}, len(attrs))
	for _i := range attrs {
		_va[_i] = attrs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, err)
	_ca = append(_ca, _va...)
	_mock.Called(_ca...)
	return
}

// Span_RecordError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordError'
type Span_RecordError_Call struct {
	*mock.Call
}

// RecordError is a helper method to define mock.On call
//   - err error
//   - attrs ...tracer.Attribute
func (_e *Span_Expecter) RecordError(err interface{}, attrs ...interface{}) *Span_RecordError_Call {
	return &Span_RecordError_Call{Call: _e.mock.On("RecordError",
		append([]interface{}{err}, attrs...)...)}
}

func (_c *Span_RecordError_Call) Run(run func(err error, attrs ...tracer.Attribute)) *Span_RecordError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		var arg1 []tracer.Attribute
		variadicArgs := make([]tracer.Attribute, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(tracer.Attribute)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Span_RecordError_Call) Return() *Span_RecordError_Call {
	_c.Call.Return()
	return _c
}

func (_c *Span_RecordError_Call) RunAndReturn(run func(err error, attrs ...tracer.Attribute)) *Span_RecordError_Call {
	_c.Run(run)
	return _c
}

// SetAttributes provides a mock function for the type Span
func (_mock *Span) SetAttributes(attrs ...tracer.Attribute) {
	// tracer.Attribute
	_va := make([]interface{}, len(attrs))
	for _i := range attrs {
		_va[_i] = attrs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_mock.Called(_ca...)
	return
}

// Span_SetAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAttributes'
type Span_SetAttributes_Call struct {
	*mock.Call
}

// SetAttributes is a helper method to define mock.On call
//   - attrs ...tracer.Attribute
func (_e *Span_Expecter) SetAttributes(attrs ...interface{}) *Span_SetAttributes_Call {
	return &Span_SetAttributes_Call{Call: _e.mock.On("SetAttributes",
		append([]interface{}{}, attrs...)...)}
}

func (_c *Span_SetAttributes_Call) Run(run func(attrs ...tracer.Attribute)) *Span_SetAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []tracer.Attribute
		variadicArgs := make([]tracer.Attribute, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(tracer.Attribute)
			}
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *Span_SetAttributes_Call) Return() *Span_SetAttributes_Call {
	_c.Call.Return()
	return _c
}

func (_c *Span_SetAttributes_Call) RunAndReturn(run func(attrs ...tracer.Attribute)) *Span_SetAttributes_Call {
	_c.Run(run)
	return _c
}

// SetStatus provides a mock function for the type Span
func (_mock *Span) SetStatus(code tracer.StatusCode, description string) {
	_mock.Called(code, description)
	return
}

// Span_SetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatus'
type Span_SetStatus_Call struct {
	*mock.Call
}

// SetStatus is a helper method to define mock.On call
//   - code tracer.StatusCode
//   - description string
func (_e *Span_Expecter) SetStatus(code interface{}, description interface{}) *Span_SetStatus_Call {
	return &Span_SetStatus_Call{Call: _e.mock.On("SetStatus", code, description)}
}

func (_c *Span_SetStatus_Call) Run(run func(code tracer.StatusCode, description string)) *Span_SetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 tracer.StatusCode
		if args[0] != nil {
			arg0 = args[0].(tracer.StatusCode)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Span_SetStatus_Call) Return() *Span_SetStatus_Call {
	_c.Call.Return()
	return _c
}

func (_c *Span_SetStatus_Call) RunAndReturn(run func(code tracer.StatusCode, description string)) *Span_SetStatus_Call {
	_c.Run(run)
	return _c
}

// SpanContext provides a mock function for the type Span
func (_mock *Span) SpanContext() tracer.SpanContext {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SpanContext")
	}

	var r0 tracer.SpanContext
	if returnFunc, ok := ret.Get(0).(func() tracer.SpanContext); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(tracer.SpanContext)
	}
	return r0
}

// Span_SpanContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SpanContext'
type Span_SpanContext_Call struct {
	*mock.Call
}

// SpanContext is a helper method to define mock.On call
func (_e *Span_Expecter) SpanContext() *Span_SpanContext_Call {
	return &Span_SpanContext_Call{Call: _e.mock.On("SpanContext")}
}

func (_c *Span_SpanContext_Call) Run(run func()) *Span_SpanContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Span_SpanContext_Call) Return(spanContext tracer.SpanContext) *Span_SpanContext_Call {
	_c.Call.Return(spanContext)
	return _c
}

func (_c *Span_SpanContext_Call) RunAndReturn(run func() tracer.SpanContext) *Span_SpanContext_Call {
	_c.Call.Return(run)
	return _c
}
