// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tracertest

import (
	"context"

	"github.com/fromforgesoftware/go-kit/monitoring/tracer"
	mock "github.com/stretchr/testify/mock"
)

// NewTracer creates a new instance of Tracer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTracer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Tracer {
	mock := &Tracer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Tracer is an autogenerated mock type for the Tracer type
type Tracer struct {
	mock.Mock
}

type Tracer_Expecter struct {
	mock *mock.Mock
}

func (_m *Tracer) EXPECT() *Tracer_Expecter {
	return &Tracer_Expecter{mock: &_m.Mock}
}

// Extract provides a mock function for the type Tracer
func (_mock *Tracer) Extract(ctx context.Context, carrier tracer.Carrier) context.Context {
	ret := _mock.Called(ctx, carrier)

	if len(ret) == 0 {
		panic("no return value specified for Extract")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func(context.Context, tracer.Carrier) context.Context); ok {
		r0 = returnFunc(ctx, carrier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// Tracer_Extract_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Extract'
type Tracer_Extract_Call struct {
	*mock.Call
}

// Extract is a helper method to define mock.On call
//   - ctx context.Context
//   - carrier tracer.Carrier
func (_e *Tracer_Expecter) Extract(ctx interface{}, carrier interface{}) *Tracer_Extract_Call {
	return &Tracer_Extract_Call{Call: _e.mock.On("Extract", ctx, carrier)}
}

func (_c *Tracer_Extract_Call) Run(run func(ctx context.Context, carrier tracer.Carrier)) *Tracer_Extract_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 tracer.Carrier
		if args[1] != nil {
			arg1 = args[1].(tracer.Carrier)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Tracer_Extract_Call) Return(context1 context.Context) *Tracer_Extract_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *Tracer_Extract_Call) RunAndReturn(run func(ctx context.Context, carrier tracer.Carrier) context.Context) *Tracer_Extract_Call {
	_c.Call.Return(run)
	return _c
}

// Inject provides a mock function for the type Tracer
func (_mock *Tracer) Inject(ctx context.Context, carrier tracer.Carrier) {
	_mock.Called(ctx, carrier)
	return
}

// Tracer_Inject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Inject'
type Tracer_Inject_Call struct {
	*mock.Call
}

// Inject is a helper method to define mock.On call
//   - ctx context.Context
//   - carrier tracer.Carrier
func (_e *Tracer_Expecter) Inject(ctx interface{}, carrier interface{}) *Tracer_Inject_Call {
	return &Tracer_Inject_Call{Call: _e.mock.On("Inject", ctx, carrier)}
}

func (_c *Tracer_Inject_Call) Run(run func(ctx context.Context, carrier tracer.Carrier)) *Tracer_Inject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 tracer.Carrier
		if args[1] != nil {
			arg1 = args[1].(tracer.Carrier)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Tracer_Inject_Call) Return() *Tracer_Inject_Call {
	_c.Call.Return()
	return _c
}

func (_c *Tracer_Inject_Call) RunAndReturn(run func(ctx context.Context, carrier tracer.Carrier)) *Tracer_Inject_Call {
	_c.Run(run)
	return _c
}

// Shutdown provides a mock function for the type Tracer
func (_mock *Tracer) Shutdown(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Tracer_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type Tracer_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Tracer_Expecter) Shutdown(ctx interface{}) *Tracer_Shutdown_Call {
	return &Tracer_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *Tracer_Shutdown_Call) Run(run func(ctx context.Context)) *Tracer_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Tracer_Shutdown_Call) Return(err error) *Tracer_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Tracer_Shutdown_Call) RunAndReturn(run func(ctx context.Context) error) *Tracer_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// SpanFromContext provides a mock function for the type Tracer
func (_mock *Tracer) SpanFromContext(ctx context.Context) tracer.Span {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SpanFromContext")
	}

	var r0 tracer.Span
	if returnFunc, ok := ret.Get(0).(func(context.Context) tracer.Span); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tracer.Span)
		}
	}
	return r0
}

// Tracer_SpanFromContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SpanFromContext'
type Tracer_SpanFromContext_Call struct {
	*mock.Call
}

// SpanFromContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Tracer_Expecter) SpanFromContext(ctx interface{}) *Tracer_SpanFromContext_Call {
	return &Tracer_SpanFromContext_Call{Call: _e.mock.On("SpanFromContext", ctx)}
}

func (_c *Tracer_SpanFromContext_Call) Run(run func(ctx context.Context)) *Tracer_SpanFromContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Tracer_SpanFromContext_Call) Return(span tracer.Span) *Tracer_SpanFromContext_Call {
	_c.Call.Return(span)
	return _c
}

func (_c *Tracer_SpanFromContext_Call) RunAndReturn(run func(ctx context.Context) tracer.Span) *Tracer_SpanFromContext_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type Tracer
func (_mock *Tracer) Start(ctx context.Context, name string, opts ...tracer.StartOption) (context.Context, tracer.Span) {
	// tracer.StartOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 context.Context
	var r1 tracer.Span
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...tracer.StartOption) (context.Context, tracer.Span)); ok {
		return returnFunc(ctx, name, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...tracer.StartOption) context.Context); ok {
		r0 = returnFunc(ctx, name, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...tracer.StartOption) tracer.Span); ok {
		r1 = returnFunc(ctx, name, opts...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(tracer.Span)
		}
	}
	return r0, r1
}

// Tracer_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type Tracer_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts ...tracer.StartOption
func (_e *Tracer_Expecter) Start(ctx interface{}, name interface{}, opts ...interface{}) *Tracer_Start_Call {
	return &Tracer_Start_Call{Call: _e.mock.On("Start",
		append([]interface{}{ctx, name}, opts...)...)}
}

func (_c *Tracer_Start_Call) Run(run func(ctx context.Context, name string, opts ...tracer.StartOption)) *Tracer_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []tracer.StartOption
		variadicArgs := make([]tracer.StartOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(tracer.StartOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Tracer_Start_Call) Return(context1 context.Context, span tracer.Span) *Tracer_Start_Call {
	_c.Call.Return(context1, span)
	return _c
}

func (_c *Tracer_Start_Call) RunAndReturn(run func(ctx context.Context, name string, opts ...tracer.StartOption) (context.Context, tracer.Span)) *Tracer_Start_Call {
	_c.Call.Return(run)
	return _c
}
