// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tb/grpctest/v1/test.proto

package grpctestv1

import (
	v1 "github.com/fromforgesoftware/go-kit/proto/tb/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Test struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Test) Reset() {
	*x = Test{}
	mi := &file_tb_grpctest_v1_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test) ProtoMessage() {}

func (x *Test) ProtoReflect() protoreflect.Message {
	mi := &file_tb_grpctest_v1_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test.ProtoReflect.Descriptor instead.
func (*Test) Descriptor() ([]byte, []int) {
	return file_tb_grpctest_v1_test_proto_rawDescGZIP(), []int{0}
}

func (x *Test) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DestroyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *v1.Resource           `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyRequest) Reset() {
	*x = DestroyRequest{}
	mi := &file_tb_grpctest_v1_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRequest) ProtoMessage() {}

func (x *DestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tb_grpctest_v1_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRequest.ProtoReflect.Descriptor instead.
func (*DestroyRequest) Descriptor() ([]byte, []int) {
	return file_tb_grpctest_v1_test_proto_rawDescGZIP(), []int{1}
}

func (x *DestroyRequest) GetResource() *v1.Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type DestroyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyResponse) Reset() {
	*x = DestroyResponse{}
	mi := &file_tb_grpctest_v1_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyResponse) ProtoMessage() {}

func (x *DestroyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tb_grpctest_v1_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyResponse.ProtoReflect.Descriptor instead.
func (*DestroyResponse) Descriptor() ([]byte, []int) {
	return file_tb_grpctest_v1_test_proto_rawDescGZIP(), []int{2}
}

var File_tb_grpctest_v1_test_proto protoreflect.FileDescriptor

const file_tb_grpctest_v1_test_proto_rawDesc = "" +
	"\n" +
	"\x19tb/grpctest/v1/test.proto\x12\x0etb.grpctest.v1\x1a\x14tb/v1/resource.proto\"\x1a\n" +
	"\x04Test\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"=\n" +
	"\x0eDestroyRequest\x12+\n" +
	"\bresource\x18\x01 \x01(\v2\x0f.tb.v1.ResourceR\bresource\"\x11\n" +
	"\x0fDestroyResponse2Y\n" +
	"\vTestService\x12J\n" +
	"\aDestroy\x12\x1e.tb.grpctest.v1.DestroyRequest\x1a\x1f.tb.grpctest.v1.DestroyResponseB\xbe\x01\n" +
	"\x12com.tb.grpctest.v1B\tTestProtoP\x01ZCgithub.com/fromforgesoftware/go-kit/proto/tb/grpctest/v1;grpctestv1\xa2\x02\x03TGX\xaa\x02\x0eTb.Grpctest.V1\xca\x02\x0eTb\\Grpctest\\V1\xe2\x02\x1aTb\\Grpctest\\V1\\GPBMetadata\xea\x02\x10Tb::Grpctest::V1b\x06proto3"

var (
	file_tb_grpctest_v1_test_proto_rawDescOnce sync.Once
	file_tb_grpctest_v1_test_proto_rawDescData []byte
)

func file_tb_grpctest_v1_test_proto_rawDescGZIP() []byte {
	file_tb_grpctest_v1_test_proto_rawDescOnce.Do(func() {
		file_tb_grpctest_v1_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tb_grpctest_v1_test_proto_rawDesc), len(file_tb_grpctest_v1_test_proto_rawDesc)))
	})
	return file_tb_grpctest_v1_test_proto_rawDescData
}

var file_tb_grpctest_v1_test_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tb_grpctest_v1_test_proto_goTypes = []any{
	(*Test)(nil),            // 0: tb.grpctest.v1.Test
	(*DestroyRequest)(nil),  // 1: tb.grpctest.v1.DestroyRequest
	(*DestroyResponse)(nil), // 2: tb.grpctest.v1.DestroyResponse
	(*v1.Resource)(nil),     // 3: tb.v1.Resource
}
var file_tb_grpctest_v1_test_proto_depIdxs = []int32{
	3, // 0: tb.grpctest.v1.DestroyRequest.resource:type_name -> tb.v1.Resource
	1, // 1: tb.grpctest.v1.TestService.Destroy:input_type -> tb.grpctest.v1.DestroyRequest
	2, // 2: tb.grpctest.v1.TestService.Destroy:output_type -> tb.grpctest.v1.DestroyResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tb_grpctest_v1_test_proto_init() }
func file_tb_grpctest_v1_test_proto_init() {
	if File_tb_grpctest_v1_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tb_grpctest_v1_test_proto_rawDesc), len(file_tb_grpctest_v1_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tb_grpctest_v1_test_proto_goTypes,
		DependencyIndexes: file_tb_grpctest_v1_test_proto_depIdxs,
		MessageInfos:      file_tb_grpctest_v1_test_proto_msgTypes,
	}.Build()
	File_tb_grpctest_v1_test_proto = out.File
	file_tb_grpctest_v1_test_proto_goTypes = nil
	file_tb_grpctest_v1_test_proto_depIdxs = nil
}
