// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jsonapitest

import (
	"github.com/fromforgesoftware/go-kit/jsonapi"
	mock "github.com/stretchr/testify/mock"
)

// NewLinkable creates a new instance of Linkable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLinkable(t interface {
	mock.TestingT
	Cleanup(func())
}) *Linkable {
	mock := &Linkable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Linkable is an autogenerated mock type for the Linkable type
type Linkable struct {
	mock.Mock
}

type Linkable_Expecter struct {
	mock *mock.Mock
}

func (_m *Linkable) EXPECT() *Linkable_Expecter {
	return &Linkable_Expecter{mock: &_m.Mock}
}

// JSONAPILinks provides a mock function for the type Linkable
func (_mock *Linkable) JSONAPILinks() *jsonapi.Links {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for JSONAPILinks")
	}

	var r0 *jsonapi.Links
	if returnFunc, ok := ret.Get(0).(func() *jsonapi.Links); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jsonapi.Links)
		}
	}
	return r0
}

// Linkable_JSONAPILinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JSONAPILinks'
type Linkable_JSONAPILinks_Call struct {
	*mock.Call
}

// JSONAPILinks is a helper method to define mock.On call
func (_e *Linkable_Expecter) JSONAPILinks() *Linkable_JSONAPILinks_Call {
	return &Linkable_JSONAPILinks_Call{Call: _e.mock.On("JSONAPILinks")}
}

func (_c *Linkable_JSONAPILinks_Call) Run(run func()) *Linkable_JSONAPILinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Linkable_JSONAPILinks_Call) Return(links *jsonapi.Links) *Linkable_JSONAPILinks_Call {
	_c.Call.Return(links)
	return _c
}

func (_c *Linkable_JSONAPILinks_Call) RunAndReturn(run func() *jsonapi.Links) *Linkable_JSONAPILinks_Call {
	_c.Call.Return(run)
	return _c
}
