// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jsonapitest

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMarshalHook creates a new instance of MarshalHook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarshalHook(t interface {
	mock.TestingT
	Cleanup(func())
}) *MarshalHook {
	mock := &MarshalHook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MarshalHook is an autogenerated mock type for the MarshalHook type
type MarshalHook struct {
	mock.Mock
}

type MarshalHook_Expecter struct {
	mock *mock.Mock
}

func (_m *MarshalHook) EXPECT() *MarshalHook_Expecter {
	return &MarshalHook_Expecter{mock: &_m.Mock}
}

// BeforeMarshal provides a mock function for the type MarshalHook
func (_mock *MarshalHook) BeforeMarshal() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BeforeMarshal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MarshalHook_BeforeMarshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeforeMarshal'
type MarshalHook_BeforeMarshal_Call struct {
	*mock.Call
}

// BeforeMarshal is a helper method to define mock.On call
func (_e *MarshalHook_Expecter) BeforeMarshal() *MarshalHook_BeforeMarshal_Call {
	return &MarshalHook_BeforeMarshal_Call{Call: _e.mock.On("BeforeMarshal")}
}

func (_c *MarshalHook_BeforeMarshal_Call) Run(run func()) *MarshalHook_BeforeMarshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MarshalHook_BeforeMarshal_Call) Return(err error) *MarshalHook_BeforeMarshal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MarshalHook_BeforeMarshal_Call) RunAndReturn(run func() error) *MarshalHook_BeforeMarshal_Call {
	_c.Call.Return(run)
	return _c
}
