// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jsonapitest

import (
	"github.com/fromforgesoftware/go-kit/jsonapi"
	mock "github.com/stretchr/testify/mock"
)

// NewMetable creates a new instance of Metable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetable(t interface {
	mock.TestingT
	Cleanup(func())
}) *Metable {
	mock := &Metable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Metable is an autogenerated mock type for the Metable type
type Metable struct {
	mock.Mock
}

type Metable_Expecter struct {
	mock *mock.Mock
}

func (_m *Metable) EXPECT() *Metable_Expecter {
	return &Metable_Expecter{mock: &_m.Mock}
}

// JSONAPIMeta provides a mock function for the type Metable
func (_mock *Metable) JSONAPIMeta() *jsonapi.Meta {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for JSONAPIMeta")
	}

	var r0 *jsonapi.Meta
	if returnFunc, ok := ret.Get(0).(func() *jsonapi.Meta); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jsonapi.Meta)
		}
	}
	return r0
}

// Metable_JSONAPIMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JSONAPIMeta'
type Metable_JSONAPIMeta_Call struct {
	*mock.Call
}

// JSONAPIMeta is a helper method to define mock.On call
func (_e *Metable_Expecter) JSONAPIMeta() *Metable_JSONAPIMeta_Call {
	return &Metable_JSONAPIMeta_Call{Call: _e.mock.On("JSONAPIMeta")}
}

func (_c *Metable_JSONAPIMeta_Call) Run(run func()) *Metable_JSONAPIMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Metable_JSONAPIMeta_Call) Return(meta *jsonapi.Meta) *Metable_JSONAPIMeta_Call {
	_c.Call.Return(meta)
	return _c
}

func (_c *Metable_JSONAPIMeta_Call) RunAndReturn(run func() *jsonapi.Meta) *Metable_JSONAPIMeta_Call {
	_c.Call.Return(run)
	return _c
}
