// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jsonapitest

import (
	mock "github.com/stretchr/testify/mock"
)

// NewPayloader creates a new instance of Payloader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPayloader(t interface {
	mock.TestingT
	Cleanup(func())
}) *Payloader {
	mock := &Payloader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Payloader is an autogenerated mock type for the Payloader type
type Payloader struct {
	mock.Mock
}

type Payloader_Expecter struct {
	mock *mock.Mock
}

func (_m *Payloader) EXPECT() *Payloader_Expecter {
	return &Payloader_Expecter{mock: &_m.Mock}
}

// clearIncluded provides a mock function for the type Payloader
func (_mock *Payloader) clearIncluded() {
	_mock.Called()
	return
}

// Payloader_clearIncluded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'clearIncluded'
type Payloader_clearIncluded_Call struct {
	*mock.Call
}

// clearIncluded is a helper method to define mock.On call
func (_e *Payloader_Expecter) clearIncluded() *Payloader_clearIncluded_Call {
	return &Payloader_clearIncluded_Call{Call: _e.mock.On("clearIncluded")}
}

func (_c *Payloader_clearIncluded_Call) Run(run func()) *Payloader_clearIncluded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Payloader_clearIncluded_Call) Return() *Payloader_clearIncluded_Call {
	_c.Call.Return()
	return _c
}

func (_c *Payloader_clearIncluded_Call) RunAndReturn(run func()) *Payloader_clearIncluded_Call {
	_c.Run(run)
	return _c
}
