// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jsonapitest

import (
	"github.com/fromforgesoftware/go-kit/jsonapi"
	mock "github.com/stretchr/testify/mock"
)

// NewRelationshipLinkable creates a new instance of RelationshipLinkable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRelationshipLinkable(t interface {
	mock.TestingT
	Cleanup(func())
}) *RelationshipLinkable {
	mock := &RelationshipLinkable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RelationshipLinkable is an autogenerated mock type for the RelationshipLinkable type
type RelationshipLinkable struct {
	mock.Mock
}

type RelationshipLinkable_Expecter struct {
	mock *mock.Mock
}

func (_m *RelationshipLinkable) EXPECT() *RelationshipLinkable_Expecter {
	return &RelationshipLinkable_Expecter{mock: &_m.Mock}
}

// JSONAPIRelationshipLinks provides a mock function for the type RelationshipLinkable
func (_mock *RelationshipLinkable) JSONAPIRelationshipLinks(relation string) *jsonapi.Links {
	ret := _mock.Called(relation)

	if len(ret) == 0 {
		panic("no return value specified for JSONAPIRelationshipLinks")
	}

	var r0 *jsonapi.Links
	if returnFunc, ok := ret.Get(0).(func(string) *jsonapi.Links); ok {
		r0 = returnFunc(relation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jsonapi.Links)
		}
	}
	return r0
}

// RelationshipLinkable_JSONAPIRelationshipLinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JSONAPIRelationshipLinks'
type RelationshipLinkable_JSONAPIRelationshipLinks_Call struct {
	*mock.Call
}

// JSONAPIRelationshipLinks is a helper method to define mock.On call
//   - relation string
func (_e *RelationshipLinkable_Expecter) JSONAPIRelationshipLinks(relation interface{}) *RelationshipLinkable_JSONAPIRelationshipLinks_Call {
	return &RelationshipLinkable_JSONAPIRelationshipLinks_Call{Call: _e.mock.On("JSONAPIRelationshipLinks", relation)}
}

func (_c *RelationshipLinkable_JSONAPIRelationshipLinks_Call) Run(run func(relation string)) *RelationshipLinkable_JSONAPIRelationshipLinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RelationshipLinkable_JSONAPIRelationshipLinks_Call) Return(links *jsonapi.Links) *RelationshipLinkable_JSONAPIRelationshipLinks_Call {
	_c.Call.Return(links)
	return _c
}

func (_c *RelationshipLinkable_JSONAPIRelationshipLinks_Call) RunAndReturn(run func(relation string) *jsonapi.Links) *RelationshipLinkable_JSONAPIRelationshipLinks_Call {
	_c.Call.Return(run)
	return _c
}
