// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jsonapitest

import (
	"github.com/fromforgesoftware/go-kit/jsonapi"
	mock "github.com/stretchr/testify/mock"
)

// NewRelationshipMetable creates a new instance of RelationshipMetable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRelationshipMetable(t interface {
	mock.TestingT
	Cleanup(func())
}) *RelationshipMetable {
	mock := &RelationshipMetable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RelationshipMetable is an autogenerated mock type for the RelationshipMetable type
type RelationshipMetable struct {
	mock.Mock
}

type RelationshipMetable_Expecter struct {
	mock *mock.Mock
}

func (_m *RelationshipMetable) EXPECT() *RelationshipMetable_Expecter {
	return &RelationshipMetable_Expecter{mock: &_m.Mock}
}

// JSONAPIRelationshipMeta provides a mock function for the type RelationshipMetable
func (_mock *RelationshipMetable) JSONAPIRelationshipMeta(relation string) *jsonapi.Meta {
	ret := _mock.Called(relation)

	if len(ret) == 0 {
		panic("no return value specified for JSONAPIRelationshipMeta")
	}

	var r0 *jsonapi.Meta
	if returnFunc, ok := ret.Get(0).(func(string) *jsonapi.Meta); ok {
		r0 = returnFunc(relation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jsonapi.Meta)
		}
	}
	return r0
}

// RelationshipMetable_JSONAPIRelationshipMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JSONAPIRelationshipMeta'
type RelationshipMetable_JSONAPIRelationshipMeta_Call struct {
	*mock.Call
}

// JSONAPIRelationshipMeta is a helper method to define mock.On call
//   - relation string
func (_e *RelationshipMetable_Expecter) JSONAPIRelationshipMeta(relation interface{}) *RelationshipMetable_JSONAPIRelationshipMeta_Call {
	return &RelationshipMetable_JSONAPIRelationshipMeta_Call{Call: _e.mock.On("JSONAPIRelationshipMeta", relation)}
}

func (_c *RelationshipMetable_JSONAPIRelationshipMeta_Call) Run(run func(relation string)) *RelationshipMetable_JSONAPIRelationshipMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RelationshipMetable_JSONAPIRelationshipMeta_Call) Return(meta *jsonapi.Meta) *RelationshipMetable_JSONAPIRelationshipMeta_Call {
	_c.Call.Return(meta)
	return _c
}

func (_c *RelationshipMetable_JSONAPIRelationshipMeta_Call) RunAndReturn(run func(relation string) *jsonapi.Meta) *RelationshipMetable_JSONAPIRelationshipMeta_Call {
	_c.Call.Return(run)
	return _c
}
