// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jsonapitest

import (
	mock "github.com/stretchr/testify/mock"
)

// NewUnmarshalHook creates a new instance of UnmarshalHook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnmarshalHook(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnmarshalHook {
	mock := &UnmarshalHook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UnmarshalHook is an autogenerated mock type for the UnmarshalHook type
type UnmarshalHook struct {
	mock.Mock
}

type UnmarshalHook_Expecter struct {
	mock *mock.Mock
}

func (_m *UnmarshalHook) EXPECT() *UnmarshalHook_Expecter {
	return &UnmarshalHook_Expecter{mock: &_m.Mock}
}

// AfterUnmarshal provides a mock function for the type UnmarshalHook
func (_mock *UnmarshalHook) AfterUnmarshal() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AfterUnmarshal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UnmarshalHook_AfterUnmarshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AfterUnmarshal'
type UnmarshalHook_AfterUnmarshal_Call struct {
	*mock.Call
}

// AfterUnmarshal is a helper method to define mock.On call
func (_e *UnmarshalHook_Expecter) AfterUnmarshal() *UnmarshalHook_AfterUnmarshal_Call {
	return &UnmarshalHook_AfterUnmarshal_Call{Call: _e.mock.On("AfterUnmarshal")}
}

func (_c *UnmarshalHook_AfterUnmarshal_Call) Run(run func()) *UnmarshalHook_AfterUnmarshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnmarshalHook_AfterUnmarshal_Call) Return(err error) *UnmarshalHook_AfterUnmarshal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UnmarshalHook_AfterUnmarshal_Call) RunAndReturn(run func() error) *UnmarshalHook_AfterUnmarshal_Call {
	_c.Call.Return(run)
	return _c
}
