// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package amqptest

import (
	"github.com/rabbitmq/amqp091-go"
	mock "github.com/stretchr/testify/mock"
)

// NewConnection creates a new instance of Connection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *Connection {
	mock := &Connection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Connection is an autogenerated mock type for the Connection type
type Connection struct {
	mock.Mock
}

type Connection_Expecter struct {
	mock *mock.Mock
}

func (_m *Connection) EXPECT() *Connection_Expecter {
	return &Connection_Expecter{mock: &_m.Mock}
}

// Channel provides a mock function for the type Connection
func (_mock *Connection) Channel() (*amqp091.Channel, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Channel")
	}

	var r0 *amqp091.Channel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*amqp091.Channel, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *amqp091.Channel); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*amqp091.Channel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Connection_Channel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Channel'
type Connection_Channel_Call struct {
	*mock.Call
}

// Channel is a helper method to define mock.On call
func (_e *Connection_Expecter) Channel() *Connection_Channel_Call {
	return &Connection_Channel_Call{Call: _e.mock.On("Channel")}
}

func (_c *Connection_Channel_Call) Run(run func()) *Connection_Channel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Connection_Channel_Call) Return(channel *amqp091.Channel, err error) *Connection_Channel_Call {
	_c.Call.Return(channel, err)
	return _c
}

func (_c *Connection_Channel_Call) RunAndReturn(run func() (*amqp091.Channel, error)) *Connection_Channel_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type Connection
func (_mock *Connection) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Connection_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Connection_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Connection_Expecter) Close() *Connection_Close_Call {
	return &Connection_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Connection_Close_Call) Run(run func()) *Connection_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Connection_Close_Call) Return(err error) *Connection_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Connection_Close_Call) RunAndReturn(run func() error) *Connection_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Config provides a mock function for the type Connection
func (_mock *Connection) Config() amqp091.Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 amqp091.Config
	if returnFunc, ok := ret.Get(0).(func() amqp091.Config); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(amqp091.Config)
	}
	return r0
}

// Connection_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type Connection_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *Connection_Expecter) Config() *Connection_Config_Call {
	return &Connection_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *Connection_Config_Call) Run(run func()) *Connection_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Connection_Config_Call) Return(config amqp091.Config) *Connection_Config_Call {
	_c.Call.Return(config)
	return _c
}

func (_c *Connection_Config_Call) RunAndReturn(run func() amqp091.Config) *Connection_Config_Call {
	_c.Call.Return(run)
	return _c
}
