// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package amqptest

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewConsumer creates a new instance of Consumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Consumer {
	mock := &Consumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Consumer is an autogenerated mock type for the Consumer type
type Consumer struct {
	mock.Mock
}

type Consumer_Expecter struct {
	mock *mock.Mock
}

func (_m *Consumer) EXPECT() *Consumer_Expecter {
	return &Consumer_Expecter{mock: &_m.Mock}
}

// Subscribe provides a mock function for the type Consumer
func (_mock *Consumer) Subscribe(ctx context.Context, onError func(context.Context, error)) error {
	ret := _mock.Called(ctx, onError)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(context.Context, error)) error); ok {
		r0 = returnFunc(ctx, onError)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Consumer_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type Consumer_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - onError func(context.Context, error)
func (_e *Consumer_Expecter) Subscribe(ctx interface{}, onError interface{}) *Consumer_Subscribe_Call {
	return &Consumer_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, onError)}
}

func (_c *Consumer_Subscribe_Call) Run(run func(ctx context.Context, onError func(context.Context, error))) *Consumer_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(context.Context, error)
		if args[1] != nil {
			arg1 = args[1].(func(context.Context, error))
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Consumer_Subscribe_Call) Return(err error) *Consumer_Subscribe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Consumer_Subscribe_Call) RunAndReturn(run func(ctx context.Context, onError func(context.Context, error)) error) *Consumer_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function for the type Consumer
func (_mock *Consumer) Unsubscribe(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Consumer_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type Consumer_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Consumer_Expecter) Unsubscribe(ctx interface{}) *Consumer_Unsubscribe_Call {
	return &Consumer_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe", ctx)}
}

func (_c *Consumer_Unsubscribe_Call) Run(run func(ctx context.Context)) *Consumer_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Consumer_Unsubscribe_Call) Return(err error) *Consumer_Unsubscribe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Consumer_Unsubscribe_Call) RunAndReturn(run func(ctx context.Context) error) *Consumer_Unsubscribe_Call {
	_c.Call.Return(run)
	return _c
}
