// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package amqptest

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewHandler creates a new instance of Handler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandler[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *Handler[T] {
	mock := &Handler[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Handler is an autogenerated mock type for the Handler type
type Handler[T any] struct {
	mock.Mock
}

type Handler_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *Handler[T]) EXPECT() *Handler_Expecter[T] {
	return &Handler_Expecter[T]{mock: &_m.Mock}
}

// Handle provides a mock function for the type Handler
func (_mock *Handler[T]) Handle(ctx context.Context, event T) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, T) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Handler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type Handler_Handle_Call[T any] struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - event T
func (_e *Handler_Expecter[T]) Handle(ctx interface{}, event interface{}) *Handler_Handle_Call[T] {
	return &Handler_Handle_Call[T]{Call: _e.mock.On("Handle", ctx, event)}
}

func (_c *Handler_Handle_Call[T]) Run(run func(ctx context.Context, event T)) *Handler_Handle_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 T
		if args[1] != nil {
			arg1 = args[1].(T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Handler_Handle_Call[T]) Return(err error) *Handler_Handle_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *Handler_Handle_Call[T]) RunAndReturn(run func(ctx context.Context, event T) error) *Handler_Handle_Call[T] {
	_c.Call.Return(run)
	return _c
}
