// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package amqptest

import (
	"context"

	"github.com/fromforgesoftware/go-kit/transport/amqp"
	mock "github.com/stretchr/testify/mock"
)

// NewProducer creates a new instance of Producer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProducer[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *Producer[T] {
	mock := &Producer[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Producer is an autogenerated mock type for the Producer type
type Producer[T any] struct {
	mock.Mock
}

type Producer_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *Producer[T]) EXPECT() *Producer_Expecter[T] {
	return &Producer_Expecter[T]{mock: &_m.Mock}
}

// Publish provides a mock function for the type Producer
func (_mock *Producer[T]) Publish(ctx context.Context, v T, opts ...amqp.PublishOpt) error {
	// amqp.PublishOpt
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, v)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, T, ...amqp.PublishOpt) error); ok {
		r0 = returnFunc(ctx, v, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Producer_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type Producer_Publish_Call[T any] struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - v T
//   - opts ...amqp.PublishOpt
func (_e *Producer_Expecter[T]) Publish(ctx interface{}, v interface{}, opts ...interface{}) *Producer_Publish_Call[T] {
	return &Producer_Publish_Call[T]{Call: _e.mock.On("Publish",
		append([]interface{}{ctx, v}, opts...)...)}
}

func (_c *Producer_Publish_Call[T]) Run(run func(ctx context.Context, v T, opts ...amqp.PublishOpt)) *Producer_Publish_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 T
		if args[1] != nil {
			arg1 = args[1].(T)
		}
		var arg2 []amqp.PublishOpt
		variadicArgs := make([]amqp.PublishOpt, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(amqp.PublishOpt)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Producer_Publish_Call[T]) Return(err error) *Producer_Publish_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *Producer_Publish_Call[T]) RunAndReturn(run func(ctx context.Context, v T, opts ...amqp.PublishOpt) error) *Producer_Publish_Call[T] {
	_c.Call.Return(run)
	return _c
}
