// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package firebasetest

import (
	"context"

	"github.com/fromforgesoftware/go-kit/firebase"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthAPI creates a new instance of AuthAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthAPI {
	mock := &AuthAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthAPI is an autogenerated mock type for the AuthAPI type
type AuthAPI struct {
	mock.Mock
}

type AuthAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthAPI) EXPECT() *AuthAPI_Expecter {
	return &AuthAPI_Expecter{mock: &_m.Mock}
}

// VerifyIDToken provides a mock function for the type AuthAPI
func (_mock *AuthAPI) VerifyIDToken(ctx context.Context, idToken string) (firebase.TokenClaims, error) {
	ret := _mock.Called(ctx, idToken)

	if len(ret) == 0 {
		panic("no return value specified for VerifyIDToken")
	}

	var r0 firebase.TokenClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (firebase.TokenClaims, error)); ok {
		return returnFunc(ctx, idToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) firebase.TokenClaims); ok {
		r0 = returnFunc(ctx, idToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(firebase.TokenClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, idToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthAPI_VerifyIDToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyIDToken'
type AuthAPI_VerifyIDToken_Call struct {
	*mock.Call
}

// VerifyIDToken is a helper method to define mock.On call
//   - ctx context.Context
//   - idToken string
func (_e *AuthAPI_Expecter) VerifyIDToken(ctx interface{}, idToken interface{}) *AuthAPI_VerifyIDToken_Call {
	return &AuthAPI_VerifyIDToken_Call{Call: _e.mock.On("VerifyIDToken", ctx, idToken)}
}

func (_c *AuthAPI_VerifyIDToken_Call) Run(run func(ctx context.Context, idToken string)) *AuthAPI_VerifyIDToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthAPI_VerifyIDToken_Call) Return(tokenClaims firebase.TokenClaims, err error) *AuthAPI_VerifyIDToken_Call {
	_c.Call.Return(tokenClaims, err)
	return _c
}

func (_c *AuthAPI_VerifyIDToken_Call) RunAndReturn(run func(ctx context.Context, idToken string) (firebase.TokenClaims, error)) *AuthAPI_VerifyIDToken_Call {
	_c.Call.Return(run)
	return _c
}
