// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package firebasetest

import (
	"firebase.google.com/go/v4/auth"
	"github.com/fromforgesoftware/go-kit/firebase"
	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// Auth provides a mock function for the type Client
func (_mock *Client) Auth() firebase.AuthAPI {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Auth")
	}

	var r0 firebase.AuthAPI
	if returnFunc, ok := ret.Get(0).(func() firebase.AuthAPI); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(firebase.AuthAPI)
		}
	}
	return r0
}

// Client_Auth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Auth'
type Client_Auth_Call struct {
	*mock.Call
}

// Auth is a helper method to define mock.On call
func (_e *Client_Expecter) Auth() *Client_Auth_Call {
	return &Client_Auth_Call{Call: _e.mock.On("Auth")}
}

func (_c *Client_Auth_Call) Run(run func()) *Client_Auth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_Auth_Call) Return(authAPI firebase.AuthAPI) *Client_Auth_Call {
	_c.Call.Return(authAPI)
	return _c
}

func (_c *Client_Auth_Call) RunAndReturn(run func() firebase.AuthAPI) *Client_Auth_Call {
	_c.Call.Return(run)
	return _c
}

// AuthClient provides a mock function for the type Client
func (_mock *Client) AuthClient() *auth.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AuthClient")
	}

	var r0 *auth.Client
	if returnFunc, ok := ret.Get(0).(func() *auth.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Client)
		}
	}
	return r0
}

// Client_AuthClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthClient'
type Client_AuthClient_Call struct {
	*mock.Call
}

// AuthClient is a helper method to define mock.On call
func (_e *Client_Expecter) AuthClient() *Client_AuthClient_Call {
	return &Client_AuthClient_Call{Call: _e.mock.On("AuthClient")}
}

func (_c *Client_AuthClient_Call) Run(run func()) *Client_AuthClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_AuthClient_Call) Return(client *auth.Client) *Client_AuthClient_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *Client_AuthClient_Call) RunAndReturn(run func() *auth.Client) *Client_AuthClient_Call {
	_c.Call.Return(run)
	return _c
}

// UserManagement provides a mock function for the type Client
func (_mock *Client) UserManagement() firebase.UserManagement {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserManagement")
	}

	var r0 firebase.UserManagement
	if returnFunc, ok := ret.Get(0).(func() firebase.UserManagement); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(firebase.UserManagement)
		}
	}
	return r0
}

// Client_UserManagement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserManagement'
type Client_UserManagement_Call struct {
	*mock.Call
}

// UserManagement is a helper method to define mock.On call
func (_e *Client_Expecter) UserManagement() *Client_UserManagement_Call {
	return &Client_UserManagement_Call{Call: _e.mock.On("UserManagement")}
}

func (_c *Client_UserManagement_Call) Run(run func()) *Client_UserManagement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_UserManagement_Call) Return(userManagement firebase.UserManagement) *Client_UserManagement_Call {
	_c.Call.Return(userManagement)
	return _c
}

func (_c *Client_UserManagement_Call) RunAndReturn(run func() firebase.UserManagement) *Client_UserManagement_Call {
	_c.Call.Return(run)
	return _c
}
