// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package firebasetest

import (
	mock "github.com/stretchr/testify/mock"
)

// NewUser creates a new instance of User. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *User {
	mock := &User{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// User is an autogenerated mock type for the User type
type User struct {
	mock.Mock
}

type User_Expecter struct {
	mock *mock.Mock
}

func (_m *User) EXPECT() *User_Expecter {
	return &User_Expecter{mock: &_m.Mock}
}

// Email provides a mock function for the type User
func (_mock *User) Email() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Email")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// User_Email_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Email'
type User_Email_Call struct {
	*mock.Call
}

// Email is a helper method to define mock.On call
func (_e *User_Expecter) Email() *User_Email_Call {
	return &User_Email_Call{Call: _e.mock.On("Email")}
}

func (_c *User_Email_Call) Run(run func()) *User_Email_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *User_Email_Call) Return(s string) *User_Email_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *User_Email_Call) RunAndReturn(run func() string) *User_Email_Call {
	_c.Call.Return(run)
	return _c
}

// EmailVerified provides a mock function for the type User
func (_mock *User) EmailVerified() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for EmailVerified")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// User_EmailVerified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmailVerified'
type User_EmailVerified_Call struct {
	*mock.Call
}

// EmailVerified is a helper method to define mock.On call
func (_e *User_Expecter) EmailVerified() *User_EmailVerified_Call {
	return &User_EmailVerified_Call{Call: _e.mock.On("EmailVerified")}
}

func (_c *User_EmailVerified_Call) Run(run func()) *User_EmailVerified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *User_EmailVerified_Call) Return(b bool) *User_EmailVerified_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *User_EmailVerified_Call) RunAndReturn(run func() bool) *User_EmailVerified_Call {
	_c.Call.Return(run)
	return _c
}

// FirstName provides a mock function for the type User
func (_mock *User) FirstName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FirstName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// User_FirstName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FirstName'
type User_FirstName_Call struct {
	*mock.Call
}

// FirstName is a helper method to define mock.On call
func (_e *User_Expecter) FirstName() *User_FirstName_Call {
	return &User_FirstName_Call{Call: _e.mock.On("FirstName")}
}

func (_c *User_FirstName_Call) Run(run func()) *User_FirstName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *User_FirstName_Call) Return(s string) *User_FirstName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *User_FirstName_Call) RunAndReturn(run func() string) *User_FirstName_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type User
func (_mock *User) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// User_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type User_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *User_Expecter) ID() *User_ID_Call {
	return &User_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *User_ID_Call) Run(run func()) *User_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *User_ID_Call) Return(s string) *User_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *User_ID_Call) RunAndReturn(run func() string) *User_ID_Call {
	_c.Call.Return(run)
	return _c
}

// LastName provides a mock function for the type User
func (_mock *User) LastName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LastName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// User_LastName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LastName'
type User_LastName_Call struct {
	*mock.Call
}

// LastName is a helper method to define mock.On call
func (_e *User_Expecter) LastName() *User_LastName_Call {
	return &User_LastName_Call{Call: _e.mock.On("LastName")}
}

func (_c *User_LastName_Call) Run(run func()) *User_LastName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *User_LastName_Call) Return(s string) *User_LastName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *User_LastName_Call) RunAndReturn(run func() string) *User_LastName_Call {
	_c.Call.Return(run)
	return _c
}

// Password provides a mock function for the type User
func (_mock *User) Password() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Password")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// User_Password_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Password'
type User_Password_Call struct {
	*mock.Call
}

// Password is a helper method to define mock.On call
func (_e *User_Expecter) Password() *User_Password_Call {
	return &User_Password_Call{Call: _e.mock.On("Password")}
}

func (_c *User_Password_Call) Run(run func()) *User_Password_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *User_Password_Call) Return(s string) *User_Password_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *User_Password_Call) RunAndReturn(run func() string) *User_Password_Call {
	_c.Call.Return(run)
	return _c
}
