// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package firebasetest

import (
	"context"

	"github.com/fromforgesoftware/go-kit/firebase"
	mock "github.com/stretchr/testify/mock"
)

// NewUserManagement creates a new instance of UserManagement. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserManagement(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserManagement {
	mock := &UserManagement{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserManagement is an autogenerated mock type for the UserManagement type
type UserManagement struct {
	mock.Mock
}

type UserManagement_Expecter struct {
	mock *mock.Mock
}

func (_m *UserManagement) EXPECT() *UserManagement_Expecter {
	return &UserManagement_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type UserManagement
func (_mock *UserManagement) Create(ctx context.Context, user firebase.User) (firebase.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 firebase.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, firebase.User) (firebase.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, firebase.User) firebase.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(firebase.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, firebase.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserManagement_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserManagement_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user firebase.User
func (_e *UserManagement_Expecter) Create(ctx interface{}, user interface{}) *UserManagement_Create_Call {
	return &UserManagement_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *UserManagement_Create_Call) Run(run func(ctx context.Context, user firebase.User)) *UserManagement_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 firebase.User
		if args[1] != nil {
			arg1 = args[1].(firebase.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserManagement_Create_Call) Return(user1 firebase.User, err error) *UserManagement_Create_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *UserManagement_Create_Call) RunAndReturn(run func(ctx context.Context, user firebase.User) (firebase.User, error)) *UserManagement_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type UserManagement
func (_mock *UserManagement) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserManagement_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type UserManagement_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *UserManagement_Expecter) Delete(ctx interface{}, id interface{}) *UserManagement_Delete_Call {
	return &UserManagement_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *UserManagement_Delete_Call) Run(run func(ctx context.Context, id string)) *UserManagement_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserManagement_Delete_Call) Return(err error) *UserManagement_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserManagement_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *UserManagement_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type UserManagement
func (_mock *UserManagement) Get(ctx context.Context, id string) (firebase.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 firebase.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (firebase.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) firebase.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(firebase.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserManagement_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type UserManagement_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *UserManagement_Expecter) Get(ctx interface{}, id interface{}) *UserManagement_Get_Call {
	return &UserManagement_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *UserManagement_Get_Call) Run(run func(ctx context.Context, id string)) *UserManagement_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserManagement_Get_Call) Return(user firebase.User, err error) *UserManagement_Get_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserManagement_Get_Call) RunAndReturn(run func(ctx context.Context, id string) (firebase.User, error)) *UserManagement_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type UserManagement
func (_mock *UserManagement) GetByEmail(ctx context.Context, email string) (firebase.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 firebase.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (firebase.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) firebase.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(firebase.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserManagement_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type UserManagement_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserManagement_Expecter) GetByEmail(ctx interface{}, email interface{}) *UserManagement_GetByEmail_Call {
	return &UserManagement_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *UserManagement_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *UserManagement_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserManagement_GetByEmail_Call) Return(user firebase.User, err error) *UserManagement_GetByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserManagement_GetByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (firebase.User, error)) *UserManagement_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type UserManagement
func (_mock *UserManagement) Update(ctx context.Context, id string, user firebase.User) (firebase.User, error) {
	ret := _mock.Called(ctx, id, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 firebase.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, firebase.User) (firebase.User, error)); ok {
		return returnFunc(ctx, id, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, firebase.User) firebase.User); ok {
		r0 = returnFunc(ctx, id, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(firebase.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, firebase.User) error); ok {
		r1 = returnFunc(ctx, id, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserManagement_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type UserManagement_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - user firebase.User
func (_e *UserManagement_Expecter) Update(ctx interface{}, id interface{}, user interface{}) *UserManagement_Update_Call {
	return &UserManagement_Update_Call{Call: _e.mock.On("Update", ctx, id, user)}
}

func (_c *UserManagement_Update_Call) Run(run func(ctx context.Context, id string, user firebase.User)) *UserManagement_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 firebase.User
		if args[2] != nil {
			arg2 = args[2].(firebase.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserManagement_Update_Call) Return(user1 firebase.User, err error) *UserManagement_Update_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *UserManagement_Update_Call) RunAndReturn(run func(ctx context.Context, id string, user firebase.User) (firebase.User, error)) *UserManagement_Update_Call {
	_c.Call.Return(run)
	return _c
}
