// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package searchtest

import (
	"github.com/fromforgesoftware/go-kit/search"
	"github.com/fromforgesoftware/go-kit/search/query"
	mock "github.com/stretchr/testify/mock"
)

// NewSearch creates a new instance of Search. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSearch(t interface {
	mock.TestingT
	Cleanup(func())
}) *Search {
	mock := &Search{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Search is an autogenerated mock type for the Search type
type Search struct {
	mock.Mock
}

type Search_Expecter struct {
	mock *mock.Mock
}

func (_m *Search) EXPECT() *Search_Expecter {
	return &Search_Expecter{mock: &_m.Mock}
}

// Equal provides a mock function for the type Search
func (_mock *Search) Equal(another search.Search) bool {
	ret := _mock.Called(another)

	if len(ret) == 0 {
		panic("no return value specified for Equal")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(search.Search) bool); ok {
		r0 = returnFunc(another)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Search_Equal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Equal'
type Search_Equal_Call struct {
	*mock.Call
}

// Equal is a helper method to define mock.On call
//   - another search.Search
func (_e *Search_Expecter) Equal(another interface{}) *Search_Equal_Call {
	return &Search_Equal_Call{Call: _e.mock.On("Equal", another)}
}

func (_c *Search_Equal_Call) Run(run func(another search.Search)) *Search_Equal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 search.Search
		if args[0] != nil {
			arg0 = args[0].(search.Search)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Search_Equal_Call) Return(b bool) *Search_Equal_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Search_Equal_Call) RunAndReturn(run func(another search.Search) bool) *Search_Equal_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type Search
func (_mock *Search) Query() query.Query {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 query.Query
	if returnFunc, ok := ret.Get(0).(func() query.Query); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(query.Query)
		}
	}
	return r0
}

// Search_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type Search_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
func (_e *Search_Expecter) Query() *Search_Query_Call {
	return &Search_Query_Call{Call: _e.mock.On("Query")}
}

func (_c *Search_Query_Call) Run(run func()) *Search_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Search_Query_Call) Return(query1 query.Query) *Search_Query_Call {
	_c.Call.Return(query1)
	return _c
}

func (_c *Search_Query_Call) RunAndReturn(run func() query.Query) *Search_Query_Call {
	_c.Call.Return(run)
	return _c
}
