// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package grpctest

import (
	"github.com/fromforgesoftware/go-kit/transport/grpc"
	mock "github.com/stretchr/testify/mock"
)

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewController(t interface {
	mock.TestingT
	Cleanup(func())
}) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

type Controller_Expecter struct {
	mock *mock.Mock
}

func (_m *Controller) EXPECT() *Controller_Expecter {
	return &Controller_Expecter{mock: &_m.Mock}
}

// SD provides a mock function for the type Controller
func (_mock *Controller) SD() grpc.ServiceDesc {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SD")
	}

	var r0 grpc.ServiceDesc
	if returnFunc, ok := ret.Get(0).(func() grpc.ServiceDesc); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.ServiceDesc)
		}
	}
	return r0
}

// Controller_SD_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SD'
type Controller_SD_Call struct {
	*mock.Call
}

// SD is a helper method to define mock.On call
func (_e *Controller_Expecter) SD() *Controller_SD_Call {
	return &Controller_SD_Call{Call: _e.mock.On("SD")}
}

func (_c *Controller_SD_Call) Run(run func()) *Controller_SD_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Controller_SD_Call) Return(v grpc.ServiceDesc) *Controller_SD_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *Controller_SD_Call) RunAndReturn(run func() grpc.ServiceDesc) *Controller_SD_Call {
	_c.Call.Return(run)
	return _c
}
