// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package grpctest

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc/metadata"
)

// NewGRPCAuthenticator creates a new instance of GRPCAuthenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGRPCAuthenticator(t interface {
	mock.TestingT
	Cleanup(func())
}) *GRPCAuthenticator {
	mock := &GRPCAuthenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GRPCAuthenticator is an autogenerated mock type for the GRPCAuthenticator type
type GRPCAuthenticator struct {
	mock.Mock
}

type GRPCAuthenticator_Expecter struct {
	mock *mock.Mock
}

func (_m *GRPCAuthenticator) EXPECT() *GRPCAuthenticator_Expecter {
	return &GRPCAuthenticator_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type GRPCAuthenticator
func (_mock *GRPCAuthenticator) Authenticate(ctx context.Context, md metadata.MD) (context.Context, error) {
	ret := _mock.Called(ctx, md)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 context.Context
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, metadata.MD) (context.Context, error)); ok {
		return returnFunc(ctx, md)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, metadata.MD) context.Context); ok {
		r0 = returnFunc(ctx, md)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, metadata.MD) error); ok {
		r1 = returnFunc(ctx, md)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GRPCAuthenticator_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type GRPCAuthenticator_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - md metadata.MD
func (_e *GRPCAuthenticator_Expecter) Authenticate(ctx interface{}, md interface{}) *GRPCAuthenticator_Authenticate_Call {
	return &GRPCAuthenticator_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, md)}
}

func (_c *GRPCAuthenticator_Authenticate_Call) Run(run func(ctx context.Context, md metadata.MD)) *GRPCAuthenticator_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 metadata.MD
		if args[1] != nil {
			arg1 = args[1].(metadata.MD)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GRPCAuthenticator_Authenticate_Call) Return(context1 context.Context, err error) *GRPCAuthenticator_Authenticate_Call {
	_c.Call.Return(context1, err)
	return _c
}

func (_c *GRPCAuthenticator_Authenticate_Call) RunAndReturn(run func(ctx context.Context, md metadata.MD) (context.Context, error)) *GRPCAuthenticator_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}
