// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package grpctest

import (
	"github.com/fromforgesoftware/go-kit/transport/grpc"
	mock "github.com/stretchr/testify/mock"
)

// NewHandlerMiddleware creates a new instance of HandlerMiddleware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandlerMiddleware(t interface {
	mock.TestingT
	Cleanup(func())
}) *HandlerMiddleware {
	mock := &HandlerMiddleware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HandlerMiddleware is an autogenerated mock type for the HandlerMiddleware type
type HandlerMiddleware struct {
	mock.Mock
}

type HandlerMiddleware_Expecter struct {
	mock *mock.Mock
}

func (_m *HandlerMiddleware) EXPECT() *HandlerMiddleware_Expecter {
	return &HandlerMiddleware_Expecter{mock: &_m.Mock}
}

// Intercept provides a mock function for the type HandlerMiddleware
func (_mock *HandlerMiddleware) Intercept(handler grpc.Handler) grpc.Handler {
	ret := _mock.Called(handler)

	if len(ret) == 0 {
		panic("no return value specified for Intercept")
	}

	var r0 grpc.Handler
	if returnFunc, ok := ret.Get(0).(func(grpc.Handler) grpc.Handler); ok {
		r0 = returnFunc(handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.Handler)
		}
	}
	return r0
}

// HandlerMiddleware_Intercept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Intercept'
type HandlerMiddleware_Intercept_Call struct {
	*mock.Call
}

// Intercept is a helper method to define mock.On call
//   - handler grpc.Handler
func (_e *HandlerMiddleware_Expecter) Intercept(handler interface{}) *HandlerMiddleware_Intercept_Call {
	return &HandlerMiddleware_Intercept_Call{Call: _e.mock.On("Intercept", handler)}
}

func (_c *HandlerMiddleware_Intercept_Call) Run(run func(handler grpc.Handler)) *HandlerMiddleware_Intercept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 grpc.Handler
		if args[0] != nil {
			arg0 = args[0].(grpc.Handler)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HandlerMiddleware_Intercept_Call) Return(handler1 grpc.Handler) *HandlerMiddleware_Intercept_Call {
	_c.Call.Return(handler1)
	return _c
}

func (_c *HandlerMiddleware_Intercept_Call) RunAndReturn(run func(handler grpc.Handler) grpc.Handler) *HandlerMiddleware_Intercept_Call {
	_c.Call.Return(run)
	return _c
}
