// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package grpctest

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMiddleware creates a new instance of Middleware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMiddleware(t interface {
	mock.TestingT
	Cleanup(func())
}) *Middleware {
	mock := &Middleware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Middleware is an autogenerated mock type for the Middleware type
type Middleware struct {
	mock.Mock
}

type Middleware_Expecter struct {
	mock *mock.Mock
}

func (_m *Middleware) EXPECT() *Middleware_Expecter {
	return &Middleware_Expecter{mock: &_m.Mock}
}

// Intercept provides a mock function for the type Middleware
func (_mock *Middleware) Intercept(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {
	ret := _mock.Called(ctx, req, info, handler)

	if len(ret) == 0 {
		panic("no return value specified for Intercept")
	}

	var r0 interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, *grpc.UnaryServerInfo, grpc.UnaryHandler) (interface{}, error)); ok {
		return returnFunc(ctx, req, info, handler)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, *grpc.UnaryServerInfo, grpc.UnaryHandler) interface{}); ok {
		r0 = returnFunc(ctx, req, info, handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, *grpc.UnaryServerInfo, grpc.UnaryHandler) error); ok {
		r1 = returnFunc(ctx, req, info, handler)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Middleware_Intercept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Intercept'
type Middleware_Intercept_Call struct {
	*mock.Call
}

// Intercept is a helper method to define mock.On call
//   - ctx context.Context
//   - req interface{}
//   - info *grpc.UnaryServerInfo
//   - handler grpc.UnaryHandler
func (_e *Middleware_Expecter) Intercept(ctx interface{}, req interface{}, info interface{}, handler interface{}) *Middleware_Intercept_Call {
	return &Middleware_Intercept_Call{Call: _e.mock.On("Intercept", ctx, req, info, handler)}
}

func (_c *Middleware_Intercept_Call) Run(run func(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler)) *Middleware_Intercept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 *grpc.UnaryServerInfo
		if args[2] != nil {
			arg2 = args[2].(*grpc.UnaryServerInfo)
		}
		var arg3 grpc.UnaryHandler
		if args[3] != nil {
			arg3 = args[3].(grpc.UnaryHandler)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Middleware_Intercept_Call) Return(resp interface{}, err error) *Middleware_Intercept_Call {
	_c.Call.Return(resp, err)
	return _c
}

func (_c *Middleware_Intercept_Call) RunAndReturn(run func(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error)) *Middleware_Intercept_Call {
	_c.Call.Return(run)
	return _c
}
