// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authtest

import (
	"context"

	"github.com/fromforgesoftware/go-kit/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewContextInjector creates a new instance of ContextInjector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContextInjector(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContextInjector {
	mock := &ContextInjector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ContextInjector is an autogenerated mock type for the ContextInjector type
type ContextInjector struct {
	mock.Mock
}

type ContextInjector_Expecter struct {
	mock *mock.Mock
}

func (_m *ContextInjector) EXPECT() *ContextInjector_Expecter {
	return &ContextInjector_Expecter{mock: &_m.Mock}
}

// Inject provides a mock function for the type ContextInjector
func (_mock *ContextInjector) Inject(ctx context.Context, token auth.Token) (context.Context, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Inject")
	}

	var r0 context.Context
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.Token) (context.Context, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.Token) context.Context); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auth.Token) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ContextInjector_Inject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Inject'
type ContextInjector_Inject_Call struct {
	*mock.Call
}

// Inject is a helper method to define mock.On call
//   - ctx context.Context
//   - token auth.Token
func (_e *ContextInjector_Expecter) Inject(ctx interface{}, token interface{}) *ContextInjector_Inject_Call {
	return &ContextInjector_Inject_Call{Call: _e.mock.On("Inject", ctx, token)}
}

func (_c *ContextInjector_Inject_Call) Run(run func(ctx context.Context, token auth.Token)) *ContextInjector_Inject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.Token
		if args[1] != nil {
			arg1 = args[1].(auth.Token)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ContextInjector_Inject_Call) Return(context1 context.Context, err error) *ContextInjector_Inject_Call {
	_c.Call.Return(context1, err)
	return _c
}

func (_c *ContextInjector_Inject_Call) RunAndReturn(run func(ctx context.Context, token auth.Token) (context.Context, error)) *ContextInjector_Inject_Call {
	_c.Call.Return(run)
	return _c
}
